### ISSUE TITLE
delta lake test fails for spark 3.3.0

### ISSUE THREAD

**Issue by tnazarew** [OpenLineage/OpenLineage#1001]
Spark integration test in `DeltaDataSourceTest.testInsertIntoDeltaSource` is failing for Spark 3.3.0 with:
```
io.openlineage.spark.agent.lifecycle.DeltaDataSourceTest testInsertIntoDeltaSource(Path, SparkSession) FAILED (40.1s)
  
java.lang.StackOverflowError

DeltaDataSourceTest > testInsertIntoDeltaSource(Path, SparkSession) FAILED
    java.lang.StackOverflowError
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
``` 

Currently there is no info about official delta-lake version supporting 3.3.0, so the test is excluded. 
This should be changed when appropriate version of delta is released.

**Comment by pawel-big-lebowski** [comment]
https://github.com/OpenLineage/OpenLineage/pull/1065
