### ISSUE TITLE
The dbt `openlineage_bigquery` adapter does not support query cancellation

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#106]
Using the `openlineage_bigquery` adapter for OpenLineage throws the following error:

```
.
.
2021-07-22 00:25:58.454756 (MainThread): 17:25:58 | [33mThe openlineage_bigquery adapter does not support query cancellation. Some queries may still be running![0m
2021-07-22 00:25:58.724444 (Thread-1): [31mUnhandled error while executing model.***.***[0m
404 DELETE https://bigquery.googleapis.com/bigquery/v2/projects/***/datasets/***/tables/***__dbt_tmp?prettyPrint=false: Not found: Table ***:***.***__dbt_tmp
2021-07-22 00:25:58.375309 (Thread-1): 
Traceback (most recent call last):
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/max/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 44, in macro
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/dbt/adapters/bigquery/impl.py", line 159, in drop_relation
    client.delete_table(relation_object)
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 1717, in delete_table
    timeout=timeout,
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 685, in _call_api
    return call()
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/***/.pyenv/versions/3.7.7/envs/dbt/lib/python3.7/site-packages/google/cloud/_http.py", line 438, in api_request
    raise exceptions.from_http_response(response)
.
```

The issue might not be directly related to the query cancellation error, as in the logs, you can see an attempt for the `openlineage_bigquery` adapter to delete a tmp table that does not exist resulting in a `404` client exception. Note, the logs above were enabled via the `--debug` flag that redirects logs to `logs/dbt.log`. When using the vanilla dbt `bigquery` adapter, no error is thrown. Below, you can find the related libraries used to reproduce the error:

```
bigquery==0.0.12
dbt-bigquery==0.20.0
google-cloud-bigquery==2.16.1
google-cloud-bigquery-storage==2.4.0
marquez-dbt-bigquery==0.16.1
```

**Comment by mobuchowski** [comment]
In this case, the both the "query cancellation" and dropping relation error comes from the fact that the relevant macros are not included in source distribution, so dbt tries to use generic ones which have different semantics.

Anyway, fix with MANIFEST.in as here: https://stackoverflow.com/a/14159430 coming soon.
