### ISSUE TITLE
While Using 14.1 Jar , messages are not emitting getting exception

### ISSUE THREAD

**Issue by dadiraj** [OpenLineage/OpenLineage#1079]
Getting below error:

22/09/08 15:51:34 ERROR EventEmitter: Could not emit lineage w/ exception
io.openlineage.client.OpenLineageClientException:
at io.openlineage.client.transports.HttpTransport.throwOnHttpError(HttpTransport.java:119)
at io.openlineage.client.transports.HttpTransport.emit(HttpTransport.java:108)
at io.openlineage.client.OpenLineageClient.emit(OpenLineageClient.java:34)
at io.openlineage.spark.agent.EventEmitter.emit(EventEmitter.java:73)
at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:102)
at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:109)
at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:95)
at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:106)
at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:106)
at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1433)
at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)

**Comment by dadiraj** [comment]
please help and suggest some pointers to resolve the issue

**Comment by Anirudh181001** [comment]
I have also observed this issue. Please do update.

**Comment by dolfinus** [comment]
Is this issue still relevant? There are few tens of OpenLineage releases since 0.14.1
