### ISSUE TITLE
spark: Column lineage for InsertIntoDatasource command not supported

### ISSUE THREAD

**Issue by Anirudh181001** [OpenLineage/OpenLineage#1357]
Hi, I am running something similar here:
` df = spark.sql("""
  select 
    table1.code,
    tabl1.id + table2.id - 10 AS new_id, 
    table.name 
  from 
    table1
    join table2
  on tabel1.id = table2.id
""")`
`df.write.mode("overwrite").save("<path>")
`

The column lineage does not seem to be captured for this case...Is it possible to support capturing column lineage for these cases please? I'd be happy to help with this issue, if any help is required from my end too!
Thanks!
@pawel-big-lebowski

**Comment by pawel-big-lebowski** [comment]
Hi @Anirudh181001 , 

The good way to start with would be to write a failing test similar to the one: 
https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/spark3/src/test/java/io/openlineage/spark3/agent/lifecycle/plan/column/ColumnLevelLineageUtilsV2CatalogTest.java#L144

One can then debug here `OpenLineage.ColumnLineageDatasetFacetBuilder`:
https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/column/ColumnLevelLineageUtils.java#L36

to see what is missing to capture column lineage (input column, output column or dependencies between the columns).

**Comment by tnazarew** [comment]
Hi @Anirudh181001, this should not be an issue since 0.21.1. Could you check on your end?

**Comment by Anirudh181001** [comment]
Hi @tnazarew Yup! Tested and this isn't an issue in 0.21.1! Thanks!

**Comment by Anirudh181001** [comment]
Hi @tnazarew I noticed that column lineage is still not being captured for SaveIntoDataSource command...

**Comment by Anirudh181001** [comment]
There are cases it does capture, but also cases when it doesn't...Seems to be a bit on and off

**Comment by tnazarew** [comment]
@Anirudh181001 could you provide example queries for when it fails?

**Comment by Anirudh181001** [comment]
Yeah so its failing with this error message: 
```
ERROR PlanUtils3: Catalog org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog is unsupported
io.openlineage.spark3.agent.lifecycle.plan.catalog.UnsupportedCatalogException: org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog
 	at io.openlineage.spark3.agent.lifecycle.plan.catalog.V2SessionCatalogHandler.getDatasetIdentifier(V2SessionCatalogHandler.java:33)
 	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.lambda$getDatasetIdentifier$2(CatalogUtils3.java:61)
 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findAny(Unknown Source)
 	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:63)
 	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:46)
 	at io.openlineage.spark3.agent.utils.PlanUtils3.getDatasetIdentifier(PlanUtils3.java:78)
	at io.openlineage.spark33.agent.lifecycle.plan.CreateReplaceDatasetBuilder.apply(CreateReplaceDatasetBuilder.java:143)
	at io.openlineage.spark33.agent.lifecycle.plan.CreateReplaceDatasetBuilder.lambda$apply$0(CreateReplaceDatasetBuilder.java:71)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.openlineage.spark33.agent.lifecycle.plan.CreateReplaceDatasetBuilder.apply(CreateReplaceDatasetBuilder.java:69)
	at io.openlineage.spark33.agent.lifecycle.plan.CreateReplaceDatasetBuilder.apply(CreateReplaceDatasetBuilder.java:61)
	at io.openlineage.spark33.agent.lifecycle.plan.CreateReplaceDatasetBuilder.apply(CreateReplaceDatasetBuilder.java:38)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.apply(AbstractQueryPlanDatasetBuilder.java:94)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.apply(AbstractQueryPlanDatasetBuilder.java:85)
	at io.openlineage.spark.agent.util.PlanUtils.safeApply(PlanUtils.java:299)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.lambda$apply$0(AbstractQueryPlanDatasetBuilder.java:75)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:67)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:39)
	at io.openlineage.spark.agent.util.PlanUtils.safeApply(PlanUtils.java:299)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$null$23(OpenLineageRunEventBuilder.java:449)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:408)
 	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:296)
 	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:279)
 	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:231)
 	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:95)
 	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecEnd$1(OpenLineageSparkListener.java:100)
 	at java.base/java.util.Optional.ifPresent(Unknown Source)
 	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:100)
 	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:84)
 	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
 	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
 	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
 	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
 	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
 	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
 	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
 	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
 	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
 	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
 	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
 	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```
Not sure if this comes under the same issue, or whether I should open a new one for it.

**Comment by tnazarew** [comment]
@Anirudh181001 I think that new issue would be better as it is more specific
