### ISSUE TITLE
kafka: Spark fails to initialize KafkaTransport 

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#1544]
Reported on OL Slack.
Job submitted with
```
spark-submit --packages "io.openlineage:openlineage-spark:0.19.+" \
    --conf "spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener" \
    --conf "spark.openlineage.transport.type=kafka" \
    --conf "spark.openlineage.transport.topicName=topicname" \
    --conf "spark.openlineage.transport.localServerId=Kafka_server" \
    file.py 
```
fails with NPE
```
23/01/27 17:29:06 ERROR AsyncEventQueue: Listener OpenLineageSparkListener threw an exception
java.lang.NullPointerException
	at io.openlineage.client.transports.TransportFactory.build(TransportFactory.java:44)
	at io.openlineage.spark.agent.EventEmitter.<init>(EventEmitter.java:40)
	at io.openlineage.spark.agent.OpenLineageSparkListener.initializeContextFactoryIfNotInitialized(OpenLineageSparkListener.java:278)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onApplicationStart(OpenLineageSparkListener.java:267)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:55)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
``

**Comment by mobuchowski** [comment]
Fixed in https://github.com/OpenLineage/OpenLineage/pull/1556
