### ISSUE TITLE
[dbt] dbt parser KeyError

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1550]
Potential transient error, I only saw it once and it cleared up when I cleared the task and ran it again. Wanted to raise it here in case there is some underlying problem.

```
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 168, in <module>
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -     main()
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 153, in main
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -     events = processor.parse().events()
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 248, in parse
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -     events += self.parse_execution(context, nodes)
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 391, in parse_execution
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO -     sql = output_node['compiled_code']
[2023-02-01, 21:33:37 UTC] {subprocess.py:93} INFO - KeyError: 'compiled_code'
[2023-02-01, 21:33:37 UTC] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-01, 21:33:37 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
```

**Comment by mobuchowski** [comment]
I think compiled_code is not required anymore: https://schemas.getdbt.com/dbt/manifest/v7/index.html#tab-pane_nodes_additionalProperties_oneOf_i0_compiled_code_oneOf_i0

We should handle it.
