### ISSUE TITLE
[BUG] Trino extractor for Airflow failing

### ISSUE THREAD

**Issue by harels** [OpenLineage/OpenLineage#1554]
When trying to run TrinoOperator, the extractor is failing:

[2023-02-02, 00:09:01 UTC] {manager.py:57} ERROR - Failed to extract metadata 'catalog' task_type=TrinoOperator airflow_dag_id=*** task_id=*** airflow_run_id=scheduled__2023-02-01T00:00:00+00:00 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/manager.py", line 43, in extract_metadata
    task_metadata = extractor.extract()
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/sql_extractor.py", line 81, in extract
    database = self._get_database()
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/trino_extractor.py", line 34, in _get_database
    return self.conn.extra_dejson["catalog"]
KeyError: 'catalog'

Astronomer Runtime 7.2.0 based on Airflow 2.5.1+astro.1
Image tag: deploy-2023-01-31T12-10

**Comment by denimalpaca** [comment]
Only reference I can find to this parameter seems to be:
https://github.com/apache/airflow/commit/eae22cec9c87e8dad4d6e8599e45af1bdd452062#diff-9a702240b5127432b36cea027e9846f74943e8c20c292f4301c182c6063db880R93

which implies it's optional. So we should at the very least not assume it's mandatory in the extractor here.
