### ISSUE TITLE
`dbt-ol` wrapper tries to render unused jinja templates

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1589]
When trying to run a Snowflake profile with `dbt-ol` and a profiles.yml file with multiple profiles, jinja tries to render _all_ the jinja templates in the file, but fails when there is a missing variables to swap in.

```
[2023-02-07, 16:24:08 UTC] {subprocess.py:75} INFO - Running command: ['/usr/local/airflow/dbt_venv/bin/dbt-ol', 'run', '--project-dir', '/usr/local/airflow/include/dbt/jaffle_shop', '--models', 'stg_customers', '--profile', 'snowflake_profile']
[2023-02-07, 16:24:08 UTC] {subprocess.py:86} INFO - Output:
[2023-02-07, 16:24:08 UTC] {subprocess.py:93} INFO - ImportError occurred when trying to import numpy module.
[2023-02-07, 16:24:08 UTC] {subprocess.py:93} INFO - Running OpenLineage dbt wrapper version 0.17.0
[2023-02-07, 16:24:08 UTC] {subprocess.py:93} INFO - This wrapper will send OpenLineage events at the end of dbt execution.
[2023-02-07, 16:24:09 UTC] {subprocess.py:93} INFO - ImportError occurred when trying to import numpy module.
[2023-02-07, 16:24:09 UTC] {subprocess.py:93} INFO - Running OpenLineage dbt wrapper version 0.17.0
[2023-02-07, 16:24:09 UTC] {subprocess.py:93} INFO - This wrapper will send OpenLineage events at the end of dbt execution.
[2023-02-07, 16:24:11 UTC] {subprocess.py:93} INFO - [0m16:24:11  Running with dbt=1.3.0
[2023-02-07, 16:24:11 UTC] {subprocess.py:93} INFO - [0m16:24:11  Unable to do partial parsing because profile has changed
[2023-02-07, 16:24:13 UTC] {subprocess.py:93} INFO - [0m16:24:13  Found 5 models, 20 tests, 0 snapshots, 0 analyses, 303 macros, 0 operations, 3 seed files, 3 sources, 0 exposures, 0 metrics
[2023-02-07, 16:24:13 UTC] {subprocess.py:93} INFO - [0m16:24:13
[2023-02-07, 16:24:15 UTC] {subprocess.py:93} INFO - [0m16:24:15  Concurrency: 1 threads (target='dev')
[2023-02-07, 16:24:15 UTC] {subprocess.py:93} INFO - [0m16:24:15
[2023-02-07, 16:24:15 UTC] {subprocess.py:93} INFO - [0m16:24:15  1 of 1 START sql view model demo.stg_customers ................................. [RUN]
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16  1 of 1 OK created sql view model demo.stg_customers ............................ [[32mSUCCESS 1[0m in 1.06s]
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16  Finished running 1 view model in 0 hours 0 minutes and 3.06 seconds (3.06s).
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16  [32mCompleted successfully[0m
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16
[2023-02-07, 16:24:16 UTC] {subprocess.py:93} INFO - [0m16:24:16  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 168, in <module>
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     main()
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 153, in main
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     events = processor.parse().events()
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 220, in parse
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     profile = self.load_yaml_with_jinja(
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 330, in load_yaml_with_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     return self.render_values_jinja(environment=self.jinja_environment, value=loaded)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 341, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 341, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 341, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   [Previous line repeated 1 more time]
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 349, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     return environment.from_string(value).render()  # type: ignore
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     self.environment.handle_exception()
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     raise rewrite_traceback_stack(source=source)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "<template>", line 1, in top-level template code
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 307, in env_var
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     raise Exception(msg)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO - Exception: Env var required but not provided: 'BIGQUERY_DATASET'
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 168, in <module>
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     main()
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 153, in main
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     events = processor.parse().events()
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 220, in parse
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     profile = self.load_yaml_with_jinja(
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 330, in load_yaml_with_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     return self.render_values_jinja(environment=self.jinja_environment, value=loaded)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 341, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 341, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 341, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   [Previous line repeated 1 more time]
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 349, in render_values_jinja
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     return environment.from_string(value).render()  # type: ignore
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     self.environment.handle_exception()
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     raise rewrite_traceback_stack(source=source)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "<template>", line 1, in top-level template code
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 307, in env_var
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO -     raise Exception(msg)
[2023-02-07, 16:24:18 UTC] {subprocess.py:93} INFO - Exception: Env var required but not provided: 'BIGQUERY_DATASET'
[2023-02-07, 16:24:18 UTC] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-07, 16:24:18 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 335, in execute
    result = self.build_and_run_cmd(env=self.get_env(context))
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 260, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 225, in run_command
    self.exception_handling(result)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 163, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 1.
```

**Comment by denimalpaca** [comment]
```
[2023-02-07, 16:46:06 UTC] {subprocess.py:75} INFO - Running command: ['/usr/local/airflow/dbt_venv/bin/dbt-ol', 'run', '--project-dir', '/usr/local/airflow/include/dbt/jaffle_shop', '--models', 'stg_customers', '--profile', 'snowflake_profile']
[2023-02-07, 16:46:06 UTC] {subprocess.py:86} INFO - Output:
[2023-02-07, 16:46:06 UTC] {subprocess.py:93} INFO - ImportError occurred when trying to import numpy module.
[2023-02-07, 16:46:06 UTC] {subprocess.py:93} INFO - Running OpenLineage dbt wrapper version 0.19.2
[2023-02-07, 16:46:06 UTC] {subprocess.py:93} INFO - This wrapper will send OpenLineage events at the end of dbt execution.
[2023-02-07, 16:46:07 UTC] {subprocess.py:93} INFO - ImportError occurred when trying to import numpy module.
[2023-02-07, 16:46:07 UTC] {subprocess.py:93} INFO - Running OpenLineage dbt wrapper version 0.19.2
[2023-02-07, 16:46:07 UTC] {subprocess.py:93} INFO - This wrapper will send OpenLineage events at the end of dbt execution.
[2023-02-07, 16:46:10 UTC] {subprocess.py:93} INFO - [0m16:46:10  Running with dbt=1.3.0
[2023-02-07, 16:46:10 UTC] {subprocess.py:93} INFO - [0m16:46:10  Found 5 models, 20 tests, 0 snapshots, 0 analyses, 303 macros, 0 operations, 3 seed files, 3 sources, 0 exposures, 0 metrics
[2023-02-07, 16:46:11 UTC] {subprocess.py:93} INFO - [0m16:46:11
[2023-02-07, 16:46:13 UTC] {subprocess.py:93} INFO - [0m16:46:13  Concurrency: 1 threads (target='dev')
[2023-02-07, 16:46:13 UTC] {subprocess.py:93} INFO - [0m16:46:13
[2023-02-07, 16:46:13 UTC] {subprocess.py:93} INFO - [0m16:46:13  1 of 1 START sql view model demo.stg_customers ................................. [RUN]
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14  1 of 1 OK created sql view model demo.stg_customers ............................ [[32mSUCCESS 1[0m in 0.97s]
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14  Finished running 1 view model in 0 hours 0 minutes and 3.36 seconds (3.36s).
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14  [32mCompleted successfully[0m
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14
[2023-02-07, 16:46:14 UTC] {subprocess.py:93} INFO - [0m16:46:14  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 168, in <module>
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     main()
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 153, in main
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     events = processor.parse().events()
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 224, in parse
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     profile = self.load_yaml_with_jinja(
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 334, in load_yaml_with_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     return self.render_values_jinja(environment=self.jinja_environment, value=loaded)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 345, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 345, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 345, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   [Previous line repeated 1 more time]
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 353, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     return environment.from_string(value).render()  # type: ignore
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     self.environment.handle_exception()
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     raise rewrite_traceback_stack(source=source)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "<template>", line 1, in top-level template code
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 311, in env_var
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     raise Exception(msg)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO - Exception: Env var required but not provided: 'BIGQUERY_DATASET'
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 168, in <module>
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     main()
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/bin/dbt-ol", line 153, in main
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     events = processor.parse().events()
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 224, in parse
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     profile = self.load_yaml_with_jinja(
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 334, in load_yaml_with_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     return self.render_values_jinja(environment=self.jinja_environment, value=loaded)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 345, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 345, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 345, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     parsed_dict[key] = cls.render_values_jinja(environment, val)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   [Previous line repeated 1 more time]
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 353, in render_values_jinja
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     return environment.from_string(value).render()  # type: ignore
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     self.environment.handle_exception()
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     raise rewrite_traceback_stack(source=source)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "<template>", line 1, in top-level template code
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -   File "/usr/local/airflow/dbt_venv/lib/python3.9/site-packages/openlineage/common/provider/dbt.py", line 311, in env_var
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO -     raise Exception(msg)
[2023-02-07, 16:46:15 UTC] {subprocess.py:93} INFO - Exception: Env var required but not provided: 'BIGQUERY_DATASET'
[2023-02-07, 16:46:15 UTC] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-07, 16:46:15 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 335, in execute
    result = self.build_and_run_cmd(env=self.get_env(context))
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 260, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 225, in run_command
    self.exception_handling(result)
  File "/usr/local/lib/python3.9/site-packages/cosmos/providers/dbt/core/operators.py", line 163, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 1.
```

Breaks with 0.19.2 as well.
