### ISSUE TITLE
OpenlineageTest jsonSerialization() failed

### ISSUE THREAD

**Issue by reoxu** [OpenLineage/OpenLineage#1604]
### What is the target system?

spark

### What kind of integration is this?

- [ ] Produces OpenLineage metadata
- [X] Consumes OpenLineage metadata
- [ ] Something else

### How should this integration be implemented?

I tested the OpenlineageTest jsonSerialization(), got this error:
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.openlineage.client.OpenLineage$RunEvent` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{
  "eventType" : "START",
  "eventTime" : "2023-02-09T01:39:36.429Z",
  "run" : {
    "runId" : "a465efc3-405f-421b-8dac-8e76257fb769",
    "facets" : {
      "nominalTime" : {
        "_producer" : "producer",
        "_schemaURL" : "https://openlineage.io/spec/facets/1-0-0/NominalTimeRunFacet.json#/$defs/NominalTimeRunFacet",
        "nominalStartTime" : "2023-02-09T01:39:36.429Z",
        "nominalEndTime" : "2023-02-09T01:39:36.429Z",
        "additionalProperties" : { }
      },
      "addi"[truncated 420 chars]; line: 2, column: 3]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)`

### Where should this integration be implemented?

- [ ] In the target system
- [X] In the OpenLineage repo
- [ ] Somewhere else

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by reoxu** [comment]
Use `OpenLineageClientUtils.fromJson(json, new TypeReference<RunEvent>() {})`
