### ISSUE TITLE
java.lang.NoClassDefFoundError: io/openlineage/spark/shaded/org/apache/hc/core5/net/URLEncodedUtils

### ISSUE THREAD

**Issue by perttus** [OpenLineage/OpenLineage#1774]
OpenLineage 0.22.0 version produces Spark error. Not sure if it's related to the new version or that have disabled `spark.logicalPlan` with option `spark.openlineage.facets.disabled = [spark_unknown;spark.logicalPlan]`

Looking at the code I noticed the warning `The type URLEncodedUtils is deprecatedJava(16777221)`
https://github.com/OpenLineage/OpenLineage/blob/5e34208432c27648ed912d9aed0e7319d2ff72e4/integration/spark/app/src/main/java/io/openlineage/spark/agent/UrlParser.java#L21

Here's the error stack:
> ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoClassDefFoundError: io/openlineage/spark/shaded/org/apache/hc/core5/net/URLEncodedUtils
	at io.openlineage.spark.agent.UrlParser.parseUrl(UrlParser.java:40)
	at io.openlineage.spark.agent.ArgumentParser.lambda$parse$0(ArgumentParser.java:70)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.openlineage.spark.agent.ArgumentParser.parse(ArgumentParser.java:70)
	at io.openlineage.spark.agent.OpenLineageSparkListener.initializeContextFactoryIfNotInitialized(OpenLineageSparkListener.java:277)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onApplicationStart(OpenLineageSparkListener.java:267)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:55)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.lang.ClassNotFoundException: io.openlineage.spark.shaded.org.apache.hc.core5.net.URLEncodedUtils
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:460)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 20 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1009)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1019)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:469)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:124)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:882)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	... 25 more

**Comment by mobuchowski** [comment]
@perttus I can see the class in the jar that I downloaded from Maven and it's extractable and readable. 

```
 Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1009)
at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1019)
at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:469)
at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:124)
at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:882)
at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
```

this suggests me that the .jar you're using might have been corrupted? Can you redownload it?

**Comment by perttus** [comment]
I'm using maven for downloading the jar file with spark conf setting `spark.jars.packages` so it should be downloaded every time. I constantly get this error so I don't think it can always be corrupted.

**Comment by pawel-big-lebowski** [comment]
@perttus interesting. Are you sure it gets downloaded each time while not being cached in `.m2` local repo? The problem you desrcibe is really similar to this:
https://stackoverflow.com/questions/32090921/deploying-maven-project-throws-java-util-zip-zipexception-invalid-loc-header-b

**Comment by kacpermuda** [comment]
It looks like this issue can be closed. Feel free to reopen if I'm mistaken.
