### ISSUE TITLE
Infinite recursion exception when running Spark Streaming with Kafka

### ISSUE THREAD

**Issue by cgpoh** [OpenLineage/OpenLineage#1846]
I'm new to OpenLineage and trying test out OpenLineage by running Spark streaming from a Kafka topic and writing to another topic. My code is as follows:

```
class OpenLineageSpike extends SparkJob {
  private val logger = LoggerFactory.getLogger(this.getClass.getName)

  // Kafka Source properties
  private val KAFKA_BROKERS = System.getenv("SPARKAPP_KAFKA_BROKERS")
  private val KAFKA_TOPIC = System.getenv("SPARKAPP_KAFKA_TOPIC")
  private val KAFKA_MAX_PARTITION_FETCH_BYTES = System.getenv("SPARKAPP_KAFKA_MAX_PARTITION_FETCH_BYTES")

  // Spark properties
  private val MAX_OFFSETS_PER_TRIGGER = System.getenv("SPARKAPP_MAX_OFFSETS_PER_TRIGGER")
  private val TRIGGER_PROCESSING_TIME = System.getenv("SPARKAPP_TRIGGER_PROCESSING_TIME")
  private val CHECKPOINT_LOCATION = System.getenv("SPARKAPP_CHECKPOINT_LOCATION")

  override def run(args: Array[String]): Unit = {
    logger.info {
      "Starting OpenLineage.."
    }

    Try {
      val conf = new SparkConf()
      conf.set("spark.extraListeners", "io.openlineage.spark.agent.OpenLineageSparkListener")
      conf.set("spark.openlineage.namespace", "spark_integration")
      conf.set("spark.openlineage.transport.type", "http")
      conf.set("spark.openlineage.transport.endpoint", "/api/v1/lineage")
      conf.set("spark.openlineage.transport.url", "http://localhost:9004")
      conf.set("spark.openlineage.parentJobName", "kafkaJob")
      conf.set("spark.openlineage.appName", "OpenLineageTest")

      val spark = SparkSession
        .builder
        .appName("OpenLineageSpike")
        .master("local[*]")
        .config(conf)
        .getOrCreate()

      val df = spark
        .readStream
        .format("kafka")
        .option("kafka.bootstrap.servers", KAFKA_BROKERS)
        .option("subscribe", KAFKA_TOPIC)
        .option("includeHeaders", "false")
        .option("startingOffsets", "earliest")
        .option("maxOffsetsPerTrigger", MAX_OFFSETS_PER_TRIGGER)
        .option("kafka.max.partition.fetch.bytes", KAFKA_MAX_PARTITION_FETCH_BYTES)
        .option("failOnDataLoss", false)
        .load()

      val ds = df
        .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)")
        .writeStream
        .format("kafka")
        .option("kafka.bootstrap.servers", KAFKA_BROKERS)
        .option("topic", "openlineage.test")
        .option("checkpointLocation", CHECKPOINT_LOCATION)
        .trigger(Trigger.ProcessingTime(TRIGGER_PROCESSING_TIME))
        .start()
        .awaitTermination()

      spark.stop
    } match {
      case Success(_) => logger.info {
        "Completed successfully!"
      }
      case Failure(t) => logger.error {
        s"Job fail: ${t.getMessage}"
      }
    }
  }
}
```
When I start this Spark job, I got the the following exception:
```
11:49:45.365 [spark-listener-group-shared] WARN  io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer - Unable to writeValueAsString
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:170) ~[commons-lang-2.6.jar:2.6]
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:131) ~[commons-lang-2.6.jar:2.6]
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:95) ~[commons-lang-2.6.jar:2.6]
	at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.writeValueAsString(LogicalPlanSerializer.java:105) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.serialize(LogicalPlanSerializer.java:128) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.mapEntry(UnknownEntryFacetListener.java:77) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.build(UnknownEntryFacetListener.java:58) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$populateRun$3(OpenLineageRunEventBuilder.java:300) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at java.util.Optional.flatMap(Optional.java:294) ~[?:?]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:300) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:279) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:231) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:95) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:98) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:84) ~[openlineage-spark-0.24.0.jar:0.24.0]
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.17.jar:?]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.17.jar:?]
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381) [spark-core_2.12-3.1.1.jar:3.1.1]
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.1.1.jar:3.1.1]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions
```
Although I can see my job in Marquez (see screenshot below) but why there are no datasets or metadata in Marquez? Is it due to the above exception?
![ss](https://github.com/OpenLineage/OpenLineage/assets/11516015/2ed9619d-7c11-4029-9e51-a9c2163c9e6c)

**Comment by cgpoh** [comment]
Hi @pawel-big-lebowski , thank you for solving this issue! May I know why my spark job shown above does not produce any dataset in Marquez?

**Comment by pawel-big-lebowski** [comment]
Hi @cgpoh, we were not actively developing support for spark streaming at the moment. I believe this is the result of a limited community interest in that tooling integration so far. Please fill the ecosystem survey on openlineage.io to let us know this is important. You can also edit issue title as it is no longer valid. We'll put this into backlog and hopefully look back into this soon.

**Comment by cgpoh** [comment]
@pawel-big-lebowski , thank you for the reply! I will close this issue for now.
