### ISSUE TITLE
InvocationTargetException from OpenlineageRunEventBuilder

### ISSUE THREAD

**Issue by Anirudh181001** [OpenLineage/OpenLineage#1859]
`java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:170)
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:131)
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:95)
	at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.writeValueAsString(LogicalPlanSerializer.java:105)
	at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.serialize(LogicalPlanSerializer.java:128)
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.mapEntry(UnknownEntryFacetListener.java:77)
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.build(UnknownEntryFacetListener.java:58)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$populateRun$3(OpenLineageRunEventBuilder.java:307)
	at java.base/java.util.Optional.flatMap(Unknown Source)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:307)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:286)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:229)
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:70)
	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecStart$0(OpenLineageSparkListener.java:91)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecStart(OpenLineageSparkListener.java:91)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:82)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]-
...`

**Comment by pawel-big-lebowski** [comment]
This is another issue related to #1858. This should not be reproducible when running on an unreleased version currently available on main.
