### ISSUE TITLE
io.openlineage.client.OpenLineageClientException: io.openlineage.spark.shaded.com.fasterxml.jackson.databind.JsonMappingException: Failed to find TransportBuilder

### ISSUE THREAD

**Issue by ddave09** [OpenLineage/OpenLineage#1860]
On Version `0.25.0` when running `OpenLineage` with Spark, we are getting:

```
io.openlineage.client.OpenLineageClientException: io.openlineage.spark.shaded.com.fasterxml.jackson.databind.JsonMappingException: Failed to find TransportBuilder (through reference chain: io.openlineage.client.OpenLineageYaml["transport"])
	at io.openlineage.client.OpenLineageClientUtils.loadOpenLineageYaml(OpenLineageClientUtils.java:140)
	at io.openlineage.spark.agent.ArgumentParser.extractOpenlineageConfFromSparkConf(ArgumentParser.java:114)
	at io.openlineage.spark.agent.ArgumentParser.parse(ArgumentParser.java:78)
	at io.openlineage.spark.agent.OpenLineageSparkListener.initializeContextFactoryIfNotInitialized(OpenLineageSparkListener.java:277)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onApplicationStart(OpenLineageSparkListener.java:267)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:55)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:91)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:83)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1347)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:82)
Caused by: io.openlineage.spark.shaded.com.fasterxml.jackson.databind.JsonMappingException: Failed to find TransportBuilder (through reference chain: io.openlineage.client.OpenLineageYaml["transport"])
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1821)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at io.openlineage.client.OpenLineageClientUtils.loadOpenLineageYaml(OpenLineageClientUtils.java:138)
	... 17 more
Caused by: java.lang.IllegalArgumentException: Failed to find TransportBuilder
	at io.openlineage.client.transports.TransportResolver.lambda$getTransportBuilder$3(TransportResolver.java:38)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.openlineage.client.transports.TransportResolver.getTransportBuilder(TransportResolver.java:37)
	at io.openlineage.client.transports.TransportResolver.resolveTransportConfigByType(TransportResolver.java:16)
	at io.openlineage.client.transports.TransportConfigTypeIdResolver.typeFromId(TransportConfigTypeIdResolver.java:35)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:125)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:147)
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	... 22 more
```

We see that `OpenLineage added support for _custom transport types_ in `0.24.0` We're not sure if it's related to that. We checked with version `0.23.0` and we don't see the exception in that version.

We are using `OpenLineage` with Spark using `spark-submit`, dependency: `io.openlineage:openlineage-spark:0.23.0`

**Comment by ddave09** [comment]
I only see templates for integration and proposals, but this didn't fit those categories so I opened a blank issue. Please let me know if there is a template for bug report that I missed.

**Comment by ddave09** [comment]
We are using all the defaults.

From here: https://openlineage.io/docs/integrations/spark/
- spark.openlineage.transport.type | The transport type used for event emit, default type is console

We are not modifying any transport configs.

The only thing that come close:
- "spark.openlineage.host" -> `<marquezURL>`
- "spark.openlineage.namespace" -> `<openLineageNamespace>`

Please let me know if you need more information.

**Comment by pawel-big-lebowski** [comment]
Are you using `console` as a transport type? 
Do you have any `spark.openlineage.transport.*` entries within your config?

**Comment by ddave09** [comment]
Nope, no `spark.openlineage.transport.*` entries in our config

**Comment by reoxu** [comment]
Databricks also met this issue when using v0.25.0， v0.21.1 is ok.

**Comment by pawel-big-lebowski** [comment]
@reoxu we've merged yesterday an integration test for databricks and it's working for 0.28. and databricks cluster `13.0.x-scala2.12` and it's fine. Wondering if you still see the same.

**Comment by mattwparas** [comment]
Actually - I may have spoke too soon (or this response made me figure it out!) - we were building a fat jar to use with spark, and were discarding all of the META-INF files - once we made sure to include the open lineage services meta inf, it worked just fine

**Comment by mattwparas** [comment]
Would it make sense to resolve the transport type for anything not matched in the default group? Something that isn't one of the already supported types? That way you still have the option to add your own transport types but don't have to fuss with the META-INF for standard cases? 

I realize in this case it was user error which I'm happy I caught, but now for any fat jar bundling with `sbt assembly` for example, they'll have to take care to include the open lineage meta inf files properly.

**Comment by mattwparas** [comment]
:wave: Bumping this again - I would be willing to do the implementation if we're okay with adding back the defaults to the implementation without delegating to the meta inf file?

**Comment by pawel-big-lebowski** [comment]
Hi @mattwparas, sorry for missing your message.

Our implementation for custom transport types is working as follows. A user implements `TransportBuilder` with type `customType`. We're using ServiceLoader to find all `TransportBuilder` implementation on the class path and find one with a type specified in the config. 

You could implement something like `openlineage.transport.builderClass`=<YOUR_CLASS_NAME>`. Then, our code could not only read transport through the ServiceLoader, but also gain the ability to read it from config and create builder with `Class.forName`. Is this something you were thinking of?

Could you reveal any details on your custom transport type?

**Comment by mattwparas** [comment]
No worries! Thanks for taking a look

So we haven't actually defined any custom transport type. What was happening is that we build uber jars, and by mistake were discarding all of the meta inf files related to open lineage. Obviously this is on us and we've made the adjustment - but previous versions of the listener did not require having the meta inf directory around in order to construct the transport builder for http.

The other complication is that we have probably 2 dozen different repositories and projects depending on open lineage, who then build their own uber jars with their own configuration. In order for us to propagate the change, we'd have to adjust the way each downstream repo builds the jar. We can do this, but if possible, it would be helpful if the http transport builder did not require the existence of the meta inf directory.

**Comment by pawel-big-lebowski** [comment]
I think I get your problem now. Sorry, that it took me so long, but mistakenly I thought it is about custom transport types. 

So, while doing your uber jars, you get rid of `io.openlineage.client.transports.TransportBuilder` Meta-inf file and lose access to all the transport defined (including STANDARD transports). 

The solution would be to have an copy of transport builders:
```
io.openlineage.client.transports.HttpTransportBuilder
io.openlineage.client.transports.KafkaTransportBuilder
io.openlineage.client.transports.ConsoleTransportBuilder
io.openlineage.client.transports.FileTransportBuilder
io.openlineage.client.transports.KinesisTransportBuilder
```
somewhere within the codebase and use it that within `io.openlineage.client.transports.TransportResolver#getTransportBuilder` method. 

Please feel free to contribute on that. 

This could be just few lines around:
```
Optional<TransportBuilder> optionalBuilder =
        StreamSupport.stream(loader.spliterator(), false).filter(predicate).findFirst();
```
to ```Stream.concat(<<stream from meta inf>>, <<stream from hardcoded list>>)```. We apply `findFirst` on the stream so potential duplicates should not bother us. 

I would be happy to help with this PR.

**Comment by mattwparas** [comment]
Great! I'll work on an PR soon and tag you in it when its ready
