### ISSUE TITLE
[Spark Integration] StackOverflowError during logical plan serialisation is tearing down running Spark applications

### ISSUE THREAD

**Issue by d-m-h** [OpenLineage/OpenLineage#2082]
As the title suggests, the integration is encountering a `StackOverflowError` that tears down a running Spark application. The issue arises when a circular reference is encountered during serialisation of the events.

Example of the error:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]-><snip, because its crazy>->org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.sql.catalyst.expressions.AttributeReference["dataType"])
```

Top of the exception trace:

```
WARN LogicalPlanSerializer: Unable to writeValueAsString
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:170)
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:131)
	at org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:95)
	at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.writeValueAsString(LogicalPlanSerializer.java:105)
	at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.serialize(LogicalPlanSerializer.java:128)
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.mapEntry(UnknownEntryFacetListener.java:77)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at scala.collection.convert.Wrappers$IteratorWrapper.forEachRemaining(Wrappers.scala:30)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.build(UnknownEntryFacetListener.java:64)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$populateRun$3(OpenLineageRunEventBuilder.java:310)
	at java.util.Optional.flatMap(Optional.java:241)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:310)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:289)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:250)
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:167)
	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$onJobStart$10(OpenLineageSparkListener.java:151)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onJobStart(OpenLineageSparkListener.java:147)
```

Context:

1. We're using Hadoop, with YARN.
2. We're using Spark 3.0.3
3. We're using PySpark

Sample job to recreate the issue:

```python
from pyspark.sql import SparkSession
from pyspark.sql.functions import lit

spark = SparkSession.builder \
    .appName("OpenLineage StackOverflowError Sample") \
    .enableHiveSupport() \
    .getOrCreate()

data = [
    ("Inception", "Christopher Nolan", "Emma Thomas", "Warner Bros"),
    ("Avatar", "James Cameron", "James Cameron", "20th Century Fox"),
    ("Titanic", "James Cameron", "James Cameron", "20th Century Fox"),
]

columns = ["Film", "Director", "Producer", "Studio"]

df = spark.createDataFrame(data, columns)
df.write.mode("overwrite").saveAsTable("dmh.films")
df = spark.sql("SELECT * FROM dmh.films")
df.write.mode("overwrite").format("orc").saveAsTable("dmh.films_overwrite")
df.write.mode("ignore").format("orc").saveAsTable("dmh.films_no_overwrite")
df.write.mode("overwrite").insertInto("dmh.films_overwrite")
df.write.mode("append").insertInto("dmh.films_no_overwrite")
df.write.mode("overwrite").format("orc").save("/user/dmh/films_data")
spark.stop()
```

This is how I am submitting the job:

```bash
spark-submit --deploy-mode client \
    --packages 'io.openlineage:openlineage-spark:1.1.0' \
    --conf spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener \
    --conf spark.openlineage.transport.type=file \
    --conf spark.openlineage.transport.location="${PWD}/events.log" \
    --conf 'spark.openlineage.facets.disabled=[spark.logicalPlan;]' \
    example-app.py
```

**Comment by mobuchowski** [comment]
Can you try with this:
'spark.openlineage.facets.disabled=[spark_unknown;spark.logicalPlan]'

It's being serialized by UnknownEntryFacet

```
	at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.mapEntry(UnknownEntryFacetListener.java:77)
```

**Comment by d-m-h** [comment]
All right. I can confirm that the sample job is not torn down, when adding `spark_unknown` to the list of disabled facets.

**Comment by pawel-big-lebowski** [comment]
@d-m-h is it reproducible for newer Spark versions? We didn't plan to support `3.0.3`, especially if there is a workaround for this. 

@mobuchowski what do you think?

**Comment by d-m-h** [comment]
@pawel-big-lebowski - officially, I can't tell you. Our environment is currently limited to 2.2.x, 2.3.x, 2.4.x and 3.0.x.
