### ISSUE TITLE
[SPARK] - Spark integration fails in k8s 

### ISSUE THREAD

**Issue by drewhayward** [OpenLineage/OpenLineage#2227]
I'm writing a basic spark job to test out submitting lineage events to an HTTP server I stood up. I'm running into the following issue when submitting a spark job to our k8s environment.

The pipeline runs successfully when I omit the openlineage lines from the spark config.

Any ideas what could be causing it?

pipeline gist
```
def main(cfg: Config) -> None:
    spark = SparkSession.builder.appName(app_name).getOrCreate()

    # step 1: load
    sdf = spark.sql(f"select * from {cfg.table}")
    sdf = sdf.filter(sdf.log_name.isin(list(cfg.log_files_to_process)))
    # Step 2: agg
    sdf_agg = sdf.groupby(sdf.log_name).agg(F.mean(F.size('trackedentities_trackid')).alias('n_tracked_entities'))
    sdf_agg.show()
    # Step 3: write
    sdf_agg.write.parquet(cfg.output_table, 'overwrite')
    print('Done with pipeline.')
```

Spark invocation
```
spark-submit \
    --conf spark.jars.packages=io.openlineage:openlineage-spark:1.5.0 \
    --conf spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener \
    --conf spark.openlineage.transport.type=http \
    --conf spark.openlineage.transport.url=https://<lineage_server> \
    --conf spark.openlineage.transport.endpoint=/lineage \
    --conf spark.hadoop.hadoop.tmp.dir=/data/hadoop-spark-tmp \
    --conf spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit=22Gi \
    --conf spark.kubernetes.driver.ownPersistentVolumeClaim=true \
    --conf spark.hadoop.tmp.dir=/data/hadoop-spark-tmp \
    --conf spark.kubernetes.driver.reusePersistentVolumeClaim=true \
    --conf spark.sql.adaptive.enabled=true \
    --conf spark.sql.adaptive.coalescePartitions.enabled=true \
    --conf spark.sql.adaptive.skewJoin.enabled=true \
    --conf spark.sql.adaptive.forceOptimizeSkewedJoin=true \
    --conf spark.driver.cores=1 \
    --conf spark.driver.memory=8G \
    --conf spark.kubernetes.executor.request.cores=2 \
    --conf spark.kubernetes.executor.limit.cores=3 \
    --conf spark.executor.memory=16G \
    --conf spark.executor.memoryOverheadFactor=0.4 \
    --conf spark.executor.cores=2 \
    --conf spark.dynamicAllocation.enabled=true \
    --conf spark.dynamicAllocation.maxExecutors=2 \
    --conf spark.dynamicAllocation.executorIdleTimeout=300 \
    pipeline.py
```

Part of the stack trace:
```
23/11/03 13:11:03 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoSuchMethodError: 'scala.collection.Seq org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.children()'
  at io.openlineage.spark.agent.filters.DeltaEventFilter.lambda$isLocalRelationOnly$0(DeltaEventFilter.java:72)
  at java.base/java.util.Optional.filter(Optional.java:223)
  at io.openlineage.spark.agent.filters.DeltaEventFilter.isLocalRelationOnly(DeltaEventFilter.java:72)
  at io.openlineage.spark.agent.filters.DeltaEventFilter.isDisabled(DeltaEventFilter.java:47)
  at io.openlineage.spark.agent.filters.EventFilterUtils.lambda$isDisabled$0(EventFilterUtils.java:34)
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
  at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
  at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
  at io.openlineage.spark.agent.filters.EventFilterUtils.isDisabled(EventFilterUtils.java:35)
  at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:76)
  at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecStart$0(OpenLineageSparkListener.java:91)
  at java.base/java.util.Optional.ifPresent(Optional.java:183)
  at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecStart(OpenLineageSparkListener.java:91)
  at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:82)
  at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
  at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
  at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
  at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
  at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
  at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
  at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
  at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
  at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.scala:17)
  at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
  at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
  at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
  at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1471)
  at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

**Comment by drewhayward** [comment]
Caused by a scala version mismatch. Our docker image was built with Scala 2.13, building with 2.12 resolved this particular issue.
