### ISSUE TITLE
openlineage-spark-1.6.2 doesn't work with HTTP transport via HTTPS

### ISSUE THREAD

**Issue by hhhonzik** [OpenLineage/OpenLineage#2317]
When trying openlineage-spark on Databricks, I've encountered a `Exception in thread "spark-listener-group-shared" java.lang.NoClassDefFoundError: io/openlineage/spark/shaded/org/apache/commons/logging/LogFactory` issue.

**Problem:** this PR https://github.com/OpenLineage/OpenLineage/pull/2297 causes the transport to break

**Current workaround**: use spark-openlineage-1.5.0 

<details>
<summary><b>Exception</b></summary>

```
Exception in thread "spark-listener-group-shared" java.lang.NoClassDefFoundError: io/openlineage/spark/shaded/org/apache/commons/logging/LogFactory
	at io.openlineage.spark.shaded.org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)
	at io.openlineage.spark.shaded.org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:970)
	at io.openlineage.client.transports.HttpTransport.withTimeout(HttpTransport.java:67)
	at io.openlineage.client.transports.HttpTransport.<init>(HttpTransport.java:50)
	at io.openlineage.client.transports.HttpTransportBuilder.build(HttpTransportBuilder.java:17)
	at io.openlineage.client.transports.TransportResolver.resolveTransportByConfig(TransportResolver.java:29)
	at io.openlineage.client.transports.TransportFactory.build(TransportFactory.java:33)
	at io.openlineage.spark.agent.EventEmitter.<init>(EventEmitter.java:55)
	at io.openlineage.spark.agent.OpenLineageSparkListener.initializeContextFactoryIfNotInitialized(OpenLineageSparkListener.java:278)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onApplicationStart(OpenLineageSparkListener.java:267)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:55)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:42)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:42)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:114)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:114)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:109)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:105)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1598)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:105)
Caused by: java.lang.ClassNotFoundException: io.openlineage.spark.shaded.org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 24 more

```
</details>

**Comment by pawel-big-lebowski** [comment]
Ahoj @hhhonzik, thanks for finding this.

I think the problem can be solved with this PR -> https://github.com/OpenLineage/OpenLineage/pull/2319/files
The thing I don't like is that this was not caught by our integration tests. 
Are you able to reproduces it locally in local spark docker? 
I am wondering if we can catch it, create test and prevent causing same issue in future.
