### ISSUE TITLE
[SPARK] 

### ISSUE THREAD

**Issue by d-m-h** [OpenLineage/OpenLineage#2459]
During the integration tests, I notice these Stack traces:

```
ColumnLineageIntegrationTest STANDARD_OUT
    2024-02-22 18:45:23 ERROR io.openlineage.spark.agent.util.PlanUtils - Apply failed:
    java.lang.ClassCastException: org.apache.spark.sql.catalyst.analysis.ResolvedIdentifier cannot be cast to org.apache.spark.sql.catalyst.analysis.ResolvedTable
        at io.openlineage.spark3.agent.lifecycle.plan.DropTableVisitor.apply(DropTableVisitor.java:34) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark3.agent.lifecycle.plan.DropTableVisitor.apply(DropTableVisitor.java:25) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.util.PlanUtils$1.lambda$apply$2(PlanUtils.java:97) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
// snip
        at io.openlineage.spark.agent.util.PlanUtils$1.apply(PlanUtils.java:113) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.util.PlanUtils$1.apply(PlanUtils.java:77) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
// snip
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$visitLogicalPlan$14(OpenLineageRunEventBuilder.java:417) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.util.ScalaConversionUtils$3.apply(ScalaConversionUtils.java:176) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$buildOutputDatasets$15(OpenLineageRunEventBuilder.java:432) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_392]
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:432) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:321) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:304) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:235) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:90) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$null$0(OpenLineageSparkListener.java:102) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:?]
        at io.openlineage.client.circuitBreaker.NoOpCircuitBreaker.run(NoOpCircuitBreaker.java:27) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:1.9.0-SNAPSHOT]
        at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecStart$1(OpenLineageSparkListener.java:100) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_392]
        at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecStart(OpenLineageSparkListener.java:98) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:?]
        at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:89) ~[openlineage-spark-agent_2.12-1.9.0-SNAPSHOT-shadow.jar:?]
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.17.jar:?]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.17.jar:?]
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1471) [spark-core_2.12-3.4.2.jar:3.4.2]
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.4.2.jar:3.4.2]
    2024-02-22 18:45:23 INFO  org.apache.spark.scheduler.AsyncEventQueue - Process of event SparkListenerSQLExecutionStart(0,Some(0),sql at ColumnLineageIntegrationTest.java:75,org.apache.spark.sql.SparkSession.sql(SparkSession.scala:671)
    io.openlineage.spark.agent.ColumnLineageIntegrationTest.lambda$setup$0(ColumnLineageIntegrationTest.java:75)
    java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
    io.openlineage.spark.agent.ColumnLineageIntegrationTest.setup(ColumnLineageIntegrationTest.java:75)
```

This could be detrimental to lineage

**Comment by pawel-big-lebowski** [comment]
I am pretty sure this got fixed with: https://github.com/OpenLineage/OpenLineage/pull/2745
Can we close?

**Comment by LuVlk** [comment]
I am looking for a good first issue to make a contribution to this project. So I would also like to know if this can be closed.
