### ISSUE TITLE
Spark integration example fails at 1st notebook

### ISSUE THREAD

**Issue by MarkizaSckuza** [OpenLineage/OpenLineage#247]
Hi,

I used the instructions from [here](https://github.com/OpenLineage/OpenLineage/tree/main/integration/spark) to try Spark integration.

At first step in notebook I ran

```
from pyspark.sql import SparkSession

spark = (SparkSession.builder.master('local')
         .appName('sample_spark')
         .config('spark.jars.packages', 'io.openlineage:openlineage-spark:0.2.1
         .config('spark.extraListeners', 'io.openlineage.spark.agent.OpenLineageSparkListener')
         .config('spark.openlineage.url', 'http://{openlineage.client.host}/api/v1/namespaces/spark_integration/')
         .getOrCreate())
```

and got an exception:

> Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: io.openlineage#openlineage-java;0.0.1-SNAPSHOT: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1429)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Then I checked the `integration/spark/build.gradle` file and found at `line 75` in dependencies section:

> implementation 'io.openlineage:openlineage-java:0.0.1-SNAPSHOT'

**Comment by collado-mike** [comment]
This was fixed here: https://github.com/OpenLineage/OpenLineage/commit/21d1f0fbb2360d9e24e7c1eed0ea7c42cfffe73e#diff-2d71abf5c8056da373d83fdea76243c73343df1936fafe4cfa5bc6adb620c2af . Part of the `0.2.2` release that just went out
