### ISSUE TITLE
[SPARK][CLIENT-JAVA] The Spark integration doesn't relocate all of its dependencies, this causes runtime errors when older versions (< 2.x) of org.yaml:snakeyaml are on the classpath

### ISSUE THREAD

**Issue by d-m-h** [OpenLineage/OpenLineage#2536]
```
2024-03-26 11:22:04.767 ERROR org.apache.spark.util.Utils - throw uncaught fatal error in thread spark-listener-group-shared
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader, org.yaml.snakeyaml.LoaderOptions)'
	at io.openlineage.spark.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:204) ~[openlineage-spark_2.13-1.10.2.jar:1.10.2]
	at io.openlineage.spark.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:505) ~[openlineage-spark_2.13-1.10.2.jar:1.10.2]
	at io.openlineage.spark.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:407) ~[openlineage-spark_2.13-1.10.2.jar:1.10.2]
	at io.openlineage.spark.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[openlineage-spark_2.13-1.10.2.jar:1.10.2]
	at io.openlineage.spark.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809) ~[openlineage-spark_2.13-1.10.2.jar:1.10.2]
	at io.openlineage.client.OpenLineageClientUtils.deserializeInputStream(OpenLineageClientUtils.java:269) ~[openlineage-spark_2.13-1.10.2.jar:1.10.2]
```

I suggest that we produce a shaded JAR for the `openlineage-java`

**Comment by mobuchowski** [comment]
I think our idea before was that as `openlineage-java` is used mostly in integrations, the particular integration would took care of shading itself. 

The shading being done in client itself would make it harder to use some dependencies, which we actually transitively use but have to shade later - like Jackson
