### ISSUE TITLE
[SPARK] [INTEGRATION] Missing dependency in using OpenLineageSparkListener

### ISSUE THREAD

**Issue by Sbargaoui** [OpenLineage/OpenLineage#259]
## Describe the bug
Missing dependency error when following example in ```integration/spark/README.md```

## To Reproduce
Run the example as in the README (jupyter example)

## Fix
Add the missing dependency ```io.openlineage:openlineage-java:0.2.1```
```python
.config('spark.jars.packages', 'io.openlineage:openlineage-java:0.2.1')
```
## Trace
```
Ivy Default Cache set to: /home/jovyan/.ivy2/cache
The jars for the packages stored in: /home/jovyan/.ivy2/jars
io.openlineage#openlineage-spark added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-24957b2b-8ca2-4c45-9f8d-1508e4b14255;1.0
	confs: [default]
	found io.openlineage#openlineage-spark;0.2.1 in central
	found org.javassist#javassist;3.27.0-GA in central
	found com.github.ok2c.hc5#hc5-async-json;0.2.1 in central
	found org.apache.httpcomponents.core5#httpcore5;5.0 in central
	found org.apache.httpcomponents.client5#httpclient5;5.0.3 in central
	found org.apache.httpcomponents.core5#httpcore5;5.0.2 in central
	found org.apache.httpcomponents.core5#httpcore5-h2;5.0.2 in central
	found org.slf4j#slf4j-api;1.7.25 in central
	found commons-codec#commons-codec;1.13 in central
	found com.fasterxml.jackson.core#jackson-databind;2.12.2 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.12.2 in central
	found com.fasterxml.jackson.core#jackson-core;2.12.2 in central
	found com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.12.2 in central
	found com.fasterxml.jackson.module#jackson-module-scala_2.11;2.12.2 in central
	found com.thoughtworks.paranamer#paranamer;2.8 in central
:: resolution report :: resolve 3604ms :: artifacts dl 27ms
	:: modules in use:
	com.fasterxml.jackson.core#jackson-annotations;2.12.2 from central in [default]
	com.fasterxml.jackson.core#jackson-core;2.12.2 from central in [default]
	com.fasterxml.jackson.core#jackson-databind;2.12.2 from central in [default]
	com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.12.2 from central in [default]
	com.fasterxml.jackson.module#jackson-module-scala_2.11;2.12.2 from central in [default]
	com.github.ok2c.hc5#hc5-async-json;0.2.1 from central in [default]
	com.thoughtworks.paranamer#paranamer;2.8 from central in [default]
	commons-codec#commons-codec;1.13 from central in [default]
	io.openlineage#openlineage-spark;0.2.1 from central in [default]
	org.apache.httpcomponents.client5#httpclient5;5.0.3 from central in [default]
	org.apache.httpcomponents.core5#httpcore5;5.0.2 from central in [default]
	org.apache.httpcomponents.core5#httpcore5-h2;5.0.2 from central in [default]
	org.javassist#javassist;3.27.0-GA from central in [default]
	org.slf4j#slf4j-api;1.7.25 from central in [default]
	:: evicted modules:
	org.apache.httpcomponents.core5#httpcore5;5.0 by [org.apache.httpcomponents.core5#httpcore5;5.0.2] in [default]
	com.fasterxml.jackson.core#jackson-databind;2.9.6 by [com.fasterxml.jackson.core#jackson-databind;2.12.2] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   17  |   0   |   0   |   2   ||   14  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		module not found: io.openlineage#openlineage-java;0.0.1-SNAPSHOT

	==== local-m2-cache: tried

	  file:/home/jovyan/.m2/repository/io/openlineage/openlineage-java/0.0.1-SNAPSHOT/openlineage-java-0.0.1-SNAPSHOT.pom

	  -- artifact io.openlineage#openlineage-java;0.0.1-SNAPSHOT!openlineage-java.jar:

	  file:/home/jovyan/.m2/repository/io/openlineage/openlineage-java/0.0.1-SNAPSHOT/openlineage-java-0.0.1-SNAPSHOT.jar

	==== local-ivy-cache: tried

	  /home/jovyan/.ivy2/local/io.openlineage/openlineage-java/0.0.1-SNAPSHOT/ivys/ivy.xml

	  -- artifact io.openlineage#openlineage-java;0.0.1-SNAPSHOT!openlineage-java.jar:

	  /home/jovyan/.ivy2/local/io.openlineage/openlineage-java/0.0.1-SNAPSHOT/jars/openlineage-java.jar

	==== central: tried

	  https://repo1.maven.org/maven2/io/openlineage/openlineage-java/0.0.1-SNAPSHOT/openlineage-java-0.0.1-SNAPSHOT.pom

	  -- artifact io.openlineage#openlineage-java;0.0.1-SNAPSHOT!openlineage-java.jar:

	  https://repo1.maven.org/maven2/io/openlineage/openlineage-java/0.0.1-SNAPSHOT/openlineage-java-0.0.1-SNAPSHOT.jar

	==== spark-packages: tried

	  https://repos.spark-packages.org/io/openlineage/openlineage-java/0.0.1-SNAPSHOT/openlineage-java-0.0.1-SNAPSHOT.pom

	  -- artifact io.openlineage#openlineage-java;0.0.1-SNAPSHOT!openlineage-java.jar:

	  https://repos.spark-packages.org/io/openlineage/openlineage-java/0.0.1-SNAPSHOT/openlineage-java-0.0.1-SNAPSHOT.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: io.openlineage#openlineage-java;0.0.1-SNAPSHOT: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: io.openlineage#openlineage-java;0.0.1-SNAPSHOT: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1429)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by wslulciuc** [comment]
@Sbargaoui: Thanks for giving the spark integration a try! Would you like to update the spark docs to add the `OpenLineageSparkListener?`

**Comment by collado-mike** [comment]
This was just fixed- https://github.com/OpenLineage/OpenLineage/commit/21d1f0fbb2360d9e24e7c1eed0ea7c42cfffe73e#diff-2d71abf5c8056da373d83fdea76243c73343df1936fafe4cfa5bc6adb620c2af
