### ISSUE TITLE
Spark Lineage isn't emitting

### ISSUE THREAD

**Issue by idavidc** [OpenLineage/OpenLineage#2601]
2024-04-11 20:44:35,644 WARN RddExecutionContext [spark-listener-group-shared]: Unable to access job conf from RDD
java.lang.NoSuchFieldException: Field is not instance of HadoopMapRedWriteConfigUtil
	at io.openlineage.spark.agent.lifecycle.RddExecutionContext.lambda$setActiveJob$0(RddExecutionContext.java:117)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.openlineage.spark.agent.lifecycle.RddExecutionContext.setActiveJob(RddExecutionContext.java:115)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$onJobStart$9(OpenLineageSparkListener.java:168)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onJobStart(OpenLineageSparkListener.java:165)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:120)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:104)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:127)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:127)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:121)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$3.$anonfun$run$4(AsyncEventQueue.scala:117)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$3.run(AsyncEventQueue.scala:117)

**Comment by d-m-h** [comment]
@idavidc - welcome! Could you provide us with more information? For instance, which version of Spark are you running? Which version of the connector are you running? What does the environment you're running Spark inside look like? Are you able to give us a sample Spark job that can reproduce this problem?

**Comment by idavidc** [comment]
@d-m-h - Using openlineage-spark-0.18.0.jar.

Spark Version 3.3


What's the best way to give a sample spark job?

**Comment by pawel-big-lebowski** [comment]
`openlineage-spark-0.18.0.jar.` is the problem I believe. Please try first with the latest version 1.12 (https://mvnrepository.com/artifact/io.openlineage/openlineage-spark)

**Comment by d-m-h** [comment]
@idavidc - as @pawel-big-lebowski said, please try using the latest version of the integration. If that doesn't work for you, you can post a small, reproducible version of the code here in the issue. Please take care to remove any private information from the code before you paste it.

**Comment by idavidc** [comment]
@d-m-h  and @pawel-big-lebowski - The latest version worked!
