### ISSUE TITLE
spark 3 lineage

### ISSUE THREAD

**Issue by tomassatka** [OpenLineage/OpenLineage#272]
Hi Team

I am trying to run openlineage with spark 3.1.1. I have tried the version that is released 0.2.2 but also build from main from branch feature/it_spark_3 but i always get the same exception.

```
java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2.writer()Lorg/apache/spark/sql/sources/v2/writer/DataSourceWriter;
	at openlineage.spark.agent.lifecycle.plan.DatasetSourceVisitor.findDatasetSource(DatasetSourceVisitor.java:57)
	at openlineage.spark.agent.lifecycle.plan.DatasetSourceVisitor.isDefinedAt(DatasetSourceVisitor.java:33)
	at openlineage.spark.agent.lifecycle.plan.DatasetSourceVisitor.isDefinedAt(DatasetSourceVisitor.java:28)
	at openlineage.spark.agent.lifecycle.plan.wrapper.OutputDatasetVisitor.isDefinedAt(OutputDatasetVisitor.java:27)
	at openlineage.spark.agent.lifecycle.plan.wrapper.OutputDatasetVisitor.isDefinedAt(OutputDatasetVisitor.java:16)
	at scala.PartialFunction$OrElse.isDefinedAt(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.isDefinedAt(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.isDefinedAt(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.isDefinedAt(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.isDefinedAt(PartialFunction.scala:170)
	at openlineage.spark.agent.lifecycle.plan.PlanTraversal.isDefinedAt(PlanTraversal.java:32)
	at openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:87)
	at openlineage.spark.agent.OpenLineageSparkListener.lambda$onJobStart$3(OpenLineageSparkListener.java:154)
	at java.util.Optional.ifPresent(Optional.java:159)
	at openlineage.spark.agent.OpenLineageSparkListener.onJobStart(OpenLineageSparkListener.java:143)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)

```

Do i do something wrong or is spark 3 simply not yet supported? 
Thanks

**Comment by julienledem** [comment]
Spark 3 support is in progress.
The spark integration works with spark 3 in some cases but not all.
Thanks for reporting and providing the stack trace.
Do you have step to reproduce?
