### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: org.apache.spark.scheduler.SparkListenerJobStart.stageIds()Lscala/collection/immutable/Seq for openlineage-spark >= 1.16 

### ISSUE THREAD

**Issue by Akash2351** [OpenLineage/OpenLineage#2798]
### OpenLineage integration/client

Spark integration

### OpenLineage version

io.openlineage:openlineage-spark_2.12:1.16.0
io.openlineage:openlineage-spark_2.13-1.17.1

### Technology and package versions

PySpark 3.4.0
Python 3.7

### Problem details

SparkContext fails during job start with exception: 
This happens when using 1.16.0 / 1.17.1 version of openlineage-spark jar. 
But the same job works when using openlineage-spark <= 1.14.0
```
24/06/24 16:09:21 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[3] at count at NativeMethodAccessorImpl.java:0), which has no missing parents
24/06/24 16:09:21 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoSuchMethodError: org.apache.spark.scheduler.SparkListenerJobStart.stageIds()Lscala/collection/immutable/Seq;
	at io.openlineage.spark.agent.OpenLineageSparkListener.onJobStart(OpenLineageSparkListener.java:156) ~[openlineage-spark_2.13-1.17.1.jar:1.17.1]
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.15.jar:?]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.15.jar:?]
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1472) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.4.0-amzn-0.jar:3.4.0-amzn-0]
```
	
Same job works with openlineage-spark 1.14.0

```
24/06/24 16:32:52 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[3] at count at NativeMethodAccessorImpl.java:0), which has no missing parents
24/06/24 16:32:52 INFO SparkSQLExecutionContext: OpenLineage received Spark event that is configured to be skipped: SparkListenerJobStart
24/06/24 16:32:52 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 18.1 KiB, free 5.2 GiB)
24/06/24 16:32:52 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 9.0 KiB, free 5.2 GiB)
24/06/24 16:32:52 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on ip-10-1-118-125.ec2.internal:43395 (size: 9.0 KiB, free: 5.2 GiB)
24/06/24 16:32:52 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1592
24/06/24 16:32:52 INFO DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[3] at count at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
24/06/24 16:32:52 INFO YarnScheduler: Adding task set 0.0 with 1 tasks resource profile 0
24/06/24 16:3
....
```

Seems like the latest version is not skipping the "SparkListenerJobStart" event , but the earlier version (1.14) is skipping it: 
```
INFO SparkSQLExecutionContext: OpenLineage received Spark event that is configured to be skipped: SparkListenerJobStart
```

### How to reproduce

Tested with AWS EMR.
Start spark session and run any pyspark job:
Replace params within <> accordingly.  Can be tested without glue catalog from direct csv, parquet files and still same error. 

```
from pyspark import SparkContext, SparkConf
from pyspark.sql import SQLContext,SparkSession,DataFrame,Window
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql import SparkSession, Window
from datetime import date, datetime

spark_conf = SparkConf().set("spark.sql.parquet.int96RebaseModeInWrite", "LEGACY") \
            .set("spark.sql.parquet.int96RebaseModeInRead", "LEGACY") \
            .set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY") \
            .set("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY")
        
spark = SparkSession.builder.master("yarn").appName(f'{app_name}').\
            config("spark.shuffle.blockTransferService", "nio").\
            config("spark.sql.parquet.enableVectorizedReader", "false"). \
            config("spark.sql.sources.partitionOverwriteMode", "dynamic"). \
            config("spark.sql.sources.parallelPartitionDiscovery.parallelism", "10"). \
            config(conf=spark_conf).\
            config("hive.metastore.client.factory.class", "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory").\
            config("hive.metastore.glue.catalogid",<awsAccountId>).enableHiveSupport().getOrCreate()
sc = spark.sparkContext
sqlContext = SQLContext(sc, sparkSession=spark)
sc._jsc.hadoopConfiguration().set("fs.s3.cse.enabled", "false")
sc._jsc.hadoopConfiguration().set("fs.s3.sse.enabled", "false")
sc._jsc.hadoopConfiguration().set("aws.region", "us-east-1")


source_df = sqlContext.sql(f'select * from <db>.<table>')
target_df = source_df.withColumn("current_timestamp", current_timestamp())
target_df.printSchema()
logger.info('Number of records in target Dataset {}'.format(target_df.count()))

spark.stop()
...
```

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by pawel-big-lebowski** [comment]
The logs provided say `openlineage-spark_2.13` was used (you're using jar built with Scala 2.13),  while `spark-core_2.12` spark distro is Scala `2.12`. Those Scala versions are not compatible which leads to errors, especially when using Collections. 

Please make sure both Scala versions: of your Spark distro and of `openlineage-spark` are matching.

**Comment by Akash2351** [comment]
Thanks. Didnt notice the Scala versions.  Will try with same Scala versions and update this post.
