### ISSUE TITLE
OpenLineage is unable to emit lineage information of an iceberg table when I read it in Spark from a Hive metastore

### ISSUE THREAD

**Issue by rohansun** [OpenLineage/OpenLineage#2915]
Hello, I am trying to capture lineage information about an iceberg table stored in a hive metastore. This is some of my spark configuration
`spark = SparkSession.builder\`
    `.appName("test") `
    `.config("spark.sql.extensions","org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \`
    `.config("spark.sql.catalog.hive_dev","org.apache.iceberg.spark.SparkCatalog") \`
    `.config("spark.sql.catalog.hive_dev.type","hive") \`
    `.config("spark.extraListeners", "io.openlineage.spark.agent.OpenLineageSparkListener") \`
    `.config("spark.openlineage.transport.type", "http") \`
    `.config("spark.openlineage.transport.url", "http://localhost:8080") \`
    `.config("spark.openlineage.namespace", "my_namespace") \`
    `.enableHiveSupport()\`
    `.getOrCreate()`
    
When I run 
`df = spark.table("spark_catalog.db.table_ice")`
`df.show()` 
I could see the output dataframe but I cannot see the lineage information of the iceberg table in Marquez. All I see is "test.collect_limit" job with no input iceberg table to it.

As a workaround, I configured a new path based catalog
 `.config("spark.sql.catalog.iceberg_catalog", "org.apache.iceberg.spark.SparkCatalog")`
 `.config("spark.sql.catalog.iceberg_catalog.type","hadoop")`
 `.config("spark.sql.catalog.iceberg_catalog.warehouse", "$PWD/warehouse")`
 `.config("spark.sql.defaultCatalog", "iceberg_catalog")`
 
 And then created a new iceberg table using `df`,
`df = spark.table("spark_catalog.db.table_ice")`
`df.createOrReplaceTempView("view")`
`spark.sql("CREATE or REPLACE TABLE db.test USING iceberg AS SELECT * FROM view")`
`df2 = spark.table("db.test")`
`df2.show()`

This `df2 = spark.table("db.test")` emits iceberg table lineage and I can actually see it in Marquez. But creating a new iceberg table everytime from an existing iceberg table just to capture lineage information is not feasible. 

What I want is just this 
`df = spark.table("spark_catalog.db.table_ice")`
`df.show()` 
to work and automatically emit dataset lineage information.

I am using Spark 3.3.1 and --packages io.openlineage:openlineage-spark_2.12:1.18.0,org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.1.0

**Comment by dolfinus** [comment]
Have you tried `df.write.format("noop").mode("append").save()` instead of `df.show()`?

**Comment by rodrigoejcm** [comment]
im facing the same issue.
Ive tried reading one table and writing to another table - No input and outputs in the events.
Tried noop, got an error.

**Comment by dolfinus** [comment]
> Tried noop, got an error.

Please provide stacktrace

**Comment by rodrigoejcm** [comment]
```
 df = spark.read.table("icedemoctlg.playbackdb.snowflake_table")
df.write.format("noop").mode("append").save()
```

```
24/08/08 15:44:27 ERROR DataSourceV2RelationDatasetExtractor: Catalog org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation is unsupported
io.openlineage.spark3.agent.lifecycle.plan.catalog.UnsupportedCatalogException: org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation
        at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.lambda$getDatasetIdentifierFromRelation$7(CatalogUtils3.java:82)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifierFromRelation(CatalogUtils3.java:82)
        at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifierFromRelation(CatalogUtils3.java:73)
        at io.openlineage.spark3.agent.utils.DataSourceV2RelationDatasetExtractor.getDatasetIdentifierFromRelation(DataSourceV2RelationDatasetExtractor.java:116)
        at io.openlineage.spark3.agent.utils.DataSourceV2RelationDatasetExtractor.getDatasetIdentifier(DataSourceV2RelationDatasetExtractor.java:68)
        at io.openlineage.spark3.agent.utils.DataSourceV2RelationDatasetExtractor.getDatasetIdentifierExtended(DataSourceV2RelationDatasetExtractor.java:95)
        at io.openlineage.spark3.agent.utils.DataSourceV2RelationDatasetExtractor.extract(DataSourceV2RelationDatasetExtractor.java:40)
        at io.openlineage.spark3.agent.lifecycle.plan.DataSourceV2RelationOutputDatasetBuilder.apply(DataSourceV2RelationOutputDatasetBuilder.java:56)
        at io.openlineage.spark3.agent.lifecycle.plan.AppendDataDatasetBuilder.apply(AppendDataDatasetBuilder.java:48)
        at io.openlineage.spark3.agent.lifecycle.plan.AppendDataDatasetBuilder.apply(AppendDataDatasetBuilder.java:25)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.apply(AbstractQueryPlanDatasetBuilder.java:97)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.apply(AbstractQueryPlanDatasetBuilder.java:86)
        at io.openlineage.spark.agent.util.PlanUtils.safeApply(PlanUtils.java:317)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.lambda$apply$0(AbstractQueryPlanDatasetBuilder.java:76)
        at java.base/java.util.Optional.map(Optional.java:265)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:68)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:40)
        at io.openlineage.spark.agent.util.PlanUtils.safeApply(PlanUtils.java:317)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$null$29(OpenLineageRunEventBuilder.java:381)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:739)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:335)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:196)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:252)
        at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$null$16(OpenLineageSparkListener.java:200)
        at io.openlineage.client.circuitBreaker.NoOpCircuitBreaker.run(NoOpCircuitBreaker.java:27)
        at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$onJobStart$17(OpenLineageSparkListener.java:198)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onJobStart(OpenLineageSparkListener.java:194)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
INFO:__main__:Stopping Spark session...                                         
24/08/08 15:44:39 WARN DataSourceV2RelationDatasetExtractor: Couldn't find identifier for dataset in plan RelationV2[] noop-table
```

**Comment by liuchunhua** [comment]
Spark 3.3
Scala 2.12
OL 1.12.0
Iceberg 1.3.1
hive 2.3

lineage event inputs is empty,  I used QueryExecution.analyzed method instead of optimizedPlan in OpenLineageRunEventBuilder, it works.

**Comment by rodrigoejcm** [comment]
HI @liuchunhua. i dont get your point

**Comment by rohansun** [comment]
Hi, I found out that I was reading a temporary view from the hive metastore at `df = spark.table("spark_catalog.db.table_ice")` instead of a table. That is why the OpenLineage dataset metadata was not being generated.

**Comment by mobuchowski** [comment]
Please reopen if it's not fixed in the newest version
