### ISSUE TITLE
[BUG] openlineage-spark does not produce complete lineage when reading Iceberg data from a location not present in the Iceberg catalog

### ISSUE THREAD

**Issue by d-m-h** [OpenLineage/OpenLineage#2935]
### OpenLineage integration/client

Spark integration

### OpenLineage version

1.16.0+

I haven't tested anything earlier.

### Technology and package versions

Spark 3.3.x and Spark 3.5.y with the corresponding versions of Iceberg.

### Deployment details

We have two Glue Catalogs, one called 'public' and another called 'workspace'. When we ingest data, Spark connects to the 'public' catalog and stores the data in Iceberg format. In the data exploration and analysis phase, Spark clients connect to the 'workspace' catalog. Instead of connecting directly to the 'public' catalog, we use a boto3 client to retrieve the location of Iceberg's metadata.json file from the 'public' catalog. Spark uses this metadata.json file to retrieve the actual data files needed for analysis. We then perform computations on the retrieved data and write the results to the 'workspace' catalog.

### Problem details

The OpenLineage Spark integration fails to produce complete lineage when Apache Spark is instructed to directly read the _metadata.json_ file of an Iceberg table.

This stems from the fact that the integration assumes _iceberg format means we access the data through an iceberg catalog_.

Exceptions are thrown during the event processing.

```
2024-08-13 15:40:14 ERROR io.openlineage.spark.agent.lifecycle.plan.column.ColumnLevelLineageUtils - Error when invoking static method 'buildColumnLineageDatasetFacet' for Spark3
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.openlineage.spark.agent.lifecycle.plan.column.ColumnLevelLineageUtils.buildColumnLineageDatasetFacet(ColumnLevelLineageUtils.java:39) ~[openlineage-spark-shared_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$buildOutputDatasets$27(OpenLineageRunEventBuilder.java:351) ~[openlineage-spark-shared_2.13-1.20.0-SNAPSHOT.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:369) ~[openlineage-spark-shared_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:196) ~[openlineage-spark-shared_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:139) ~[main/:?]
	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecEnd$6(OpenLineageSparkListener.java:151) ~[main/:?]
Caused by: java.lang.IllegalArgumentException: Can not create a Path from a null string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:168) ~[hadoop-common-3.3.2.jar:?]
	at org.apache.hadoop.fs.Path.<init>(Path.java:184) ~[hadoop-common-3.3.2.jar:?]
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.IcebergHandler.getDatasetIdentifier(IcebergHandler.java:100) ~[openlineage-spark-spark3_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.lambda$getDatasetIdentifier$2(CatalogUtils3.java:61) ~[openlineage-spark-spark3_2.13-1.20.0-SNAPSHOT.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652) ~[?:?]
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:63) ~[openlineage-spark-spark3_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:46) ~[openlineage-spark-spark3_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark3.agent.utils.PlanUtils3.getDatasetIdentifier(PlanUtils3.java:50) ~[openlineage-spark-spark3_2.13-1.20.0-SNAPSHOT.jar:?]
	at io.openlineage.spark3.agent.utils.DataSourceV2RelationDatasetExtractor.getDatasetIdentifierExtended(DataSourceV2RelationDatasetExtractor.java:109) ~[openlineage-spark-spark3_2.13-1.20.0-SNAPSHOT.jar:?]
```

### How to reproduce

```java
package io.openlineage.spark.agent;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;
import lombok.extern.slf4j.Slf4j;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.RowFactory;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.types.DataTypes;
import org.apache.spark.sql.types.Metadata;
import org.apache.spark.sql.types.StructField;
import org.apache.spark.sql.types.StructType;
import org.junit.jupiter.api.Test;

@Slf4j
class DirectIcebergReadTest {

  static Path baseDir =
      Paths.get(System.getProperty("user.dir"))
          .resolve("build/test-output/warehouse")
          .toAbsolutePath();
  static Path sparkWarehousePath = baseDir.resolve("spark");
  static Path publicWarehouse = baseDir.resolve("public");
  static Path workspaceWarehouse = baseDir.resolve("workspace");

  @Test
  void readFromIcebergDatasetWithoutUsingCatalog() {
    log.info("Spark warehouse path: {}", sparkWarehousePath);
    log.info("Public warehouse path: {}", publicWarehouse);
    log.info("Workspace warehouse path: {}", workspaceWarehouse);
    {
      log.info("Creating an iceberg dataset");
      SparkSession spark =
          SparkSession.builder()
              .config("spark.app.name", "create-iceberg-dataset")
              .config("spark.driver.host", "localhost")
              .config("spark.master", "local[*]")
              .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
              .config("spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog")
              .config("spark.sql.catalog.spark_catalog.type", "hive")
              .config("spark.sql.catalog.public", "org.apache.iceberg.spark.SparkCatalog")
              .config("spark.sql.catalog.public.type", "hadoop")
              .config("spark.sql.catalog.public.warehouse", publicWarehouse.toString())
              .config("spark.sql.defaultCatalog", "public")
              .config("spark.sql.shuffle.partitions", "1")
              .config("spark.sql.warehouse.dir", sparkWarehousePath.toString())
              .config("spark.ui.enabled", false)
              .getOrCreate();

      spark.sql("CREATE DATABASE openlineage_public");
      spark.sql("CREATE TABLE openlineage_public.person ( first_name string NOT NULL, last_name string NOT NULL, age int NOT NULL ) USING iceberg");

      Dataset<Row> source = spark.createDataFrame(
          Collections.singletonList(RowFactory.create("Petr", "Pavel", 35)),
          new StructType()
              .add(new StructField("first_name", DataTypes.StringType, false, Metadata.empty()))
              .add(new StructField("last_name", DataTypes.StringType, false, Metadata.empty()))
              .add(new StructField("age", DataTypes.IntegerType, false, Metadata.empty())));

      source.createOrReplaceTempView("_person");
      source.show();

      spark.sql("INSERT OVERWRITE openlineage_public.person SELECT first_name, last_name, age FROM _person");
      spark.stop();
      log.info("Iceberg dataset created");
    }
    {
      log.info("Creating a derived dataset");
      SparkSession spark =
          SparkSession.builder()
              .config("spark.app.name", "create-derived-dataset")
              .config("spark.driver.host", "localhost")
              .config("spark.extraListeners", OpenLineageSparkListener.class.getCanonicalName())
              .config("spark.master", "local[*]")
              .config("spark.openlineage.namespace", "openlineage")
              .config("spark.openlineage.transport.type", "console")
              .config(
                  "spark.sql.extensions",
                  "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
              .config(
                  "spark.sql.catalog.spark_catalog", "org.apache.iceberg.spark.SparkSessionCatalog")
              .config("spark.sql.catalog.spark_catalog.type", "hive")
              .config("spark.sql.catalog.workspace", "org.apache.iceberg.spark.SparkCatalog")
              .config("spark.sql.catalog.workspace.type", "hadoop")
              .config("spark.sql.catalog.workspace.warehouse", workspaceWarehouse.toString())
              .config("spark.sql.defaultCatalog", "workspace")
              .config("spark.sql.shuffle.partitions", "1")
              .config("spark.sql.warehouse.dir", sparkWarehousePath.toString())
              .config("spark.ui.enabled", false)
              .getOrCreate();

      spark.sql("CREATE DATABASE openlineage_workspace");

      // First, we perform a direct read from the Iceberg dataset without going through a catalog
      Dataset<Row> source = spark.read().format("iceberg").load(publicWarehouse.resolve("openlineage_public/person/metadata/v2.metadata.json").toString());
      source.show();

      source.write().format("parquet").saveAsTable("openlineage_workspace.person");

      spark.stop();
      log.info("Derived dataset created");
    }
  }
}
```

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by dolfinus** [comment]
Have you tried the latest OL release?

**Comment by d-m-h** [comment]
> Have you tried the latest OL release?

This behaviour occurs in 1.19.0

**Comment by d-m-h** [comment]
OK. More information:

```json
{
    "eventTime": "2024-08-15T09:57:37.991Z",
    "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
    "schemaURL": "https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunEvent",
    "eventType": "COMPLETE",
    "run":
    {
        "runId": "01915578-b042-7e28-a50a-b8ac5cc98fa2",
        "facets":
        {
            "parent":
            {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/ParentRunFacet.json#/$defs/ParentRunFacet",
                "run":
                {
                    "runId": "01915578-ac3f-719c-b243-d4e6a0f4f45f"
                },
                "job":
                {
                    "namespace": "openlineage",
                    "name": "create_derived_dataset"
                }
            },
            "spark_properties":
            {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet",
                "properties":
                {
                    "spark.master": "local[*]",
                    "spark.app.name": "create-derived-dataset"
                }
            },
            "processing_engine":
            {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/facets/1-1-1/ProcessingEngineRunFacet.json#/$defs/ProcessingEngineRunFacet",
                "version": "3.3.4",
                "name": "spark"
            },
            "environment-properties":
            {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet",
                "environment-properties":
                {}
            }
        }
    },
    "job":
    {
        "namespace": "openlineage",
        "name": "create_derived_dataset.atomic_create_table_as_select.openlineage_workspace_person",
        "facets":
        {
            "jobType":
            {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/facets/2-0-3/JobTypeJobFacet.json#/$defs/JobTypeJobFacet",
                "processingType": "BATCH",
                "integration": "SPARK",
                "jobType": "SQL_JOB"
            }
        }
    },
    "inputs":
    [],
    "outputs":
    [
        {
            "namespace": "file",
            "name": "/home/dmh/Projects/OpenLineage/OpenLineage/integration/spark/app/build/test-output/warehouse/workspace/openlineage_workspace/person",
            "facets":
            {
                "dataSource":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet",
                    "name": "file",
                    "uri": "file"
                },
                "version":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/DatasetVersionDatasetFacet.json#/$defs/DatasetVersionDatasetFacet",
                    "datasetVersion": "8344976094574550844"
                },
                "schema":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-1-1/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet",
                    "fields":
                    [
                        {
                            "name": "first_name",
                            "type": "string"
                        },
                        {
                            "name": "last_name",
                            "type": "string"
                        },
                        {
                            "name": "age",
                            "type": "integer"
                        }
                    ]
                },
                "storage":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/StorageDatasetFacet.json#/$defs/StorageDatasetFacet",
                    "storageLayer": "iceberg",
                    "fileFormat": ""
                },
                "columnLineage":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-1-0/ColumnLineageDatasetFacet.json#/$defs/ColumnLineageDatasetFacet",
                    "fields":
                    {
                        "first_name":
                        {
                            "inputFields":
                            [
                                {
                                    "namespace": "file",
                                    "name": "/home/dmh/Projects/OpenLineage/OpenLineage/integration/spark/app/build/test-output/warehouse/public/openlineage_public/person",
                                    "field": "first_name",
                                    "transformations":
                                    [
                                        {
                                            "type": "DIRECT",
                                            "subtype": "IDENTITY",
                                            "description": "",
                                            "masking": false
                                        }
                                    ]
                                }
                            ]
                        },
                        "last_name":
                        {
                            "inputFields":
                            [
                                {
                                    "namespace": "file",
                                    "name": "/home/dmh/Projects/OpenLineage/OpenLineage/integration/spark/app/build/test-output/warehouse/public/openlineage_public/person",
                                    "field": "last_name",
                                    "transformations":
                                    [
                                        {
                                            "type": "DIRECT",
                                            "subtype": "IDENTITY",
                                            "description": "",
                                            "masking": false
                                        }
                                    ]
                                }
                            ]
                        },
                        "age":
                        {
                            "inputFields":
                            [
                                {
                                    "namespace": "file",
                                    "name": "/home/dmh/Projects/OpenLineage/OpenLineage/integration/spark/app/build/test-output/warehouse/public/openlineage_public/person",
                                    "field": "age",
                                    "transformations":
                                    [
                                        {
                                            "type": "DIRECT",
                                            "subtype": "IDENTITY",
                                            "description": "",
                                            "masking": false
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                },
                "symlinks":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/SymlinksDatasetFacet.json#/$defs/SymlinksDatasetFacet",
                    "identifiers":
                    [
                        {
                            "namespace": "file:/home/dmh/Projects/OpenLineage/OpenLineage/integration/spark/app/build/test-output/warehouse/workspace",
                            "name": "openlineage_workspace.person",
                            "type": "TABLE"
                        }
                    ]
                },
                "lifecycleStateChange":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-1/LifecycleStateChangeDatasetFacet.json#/$defs/LifecycleStateChangeDatasetFacet",
                    "lifecycleStateChange": "CREATE"
                }
            },
            "outputFacets":
            {
                "outputStatistics":
                {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.9.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-2/OutputStatisticsOutputDatasetFacet.json#/$defs/OutputStatisticsOutputDatasetFacet",
                    "rowCount": 1,
                    "size": 922
                }
            }
        }
    ]
}
```

The strangeness here is:

1. There are zero input datasets
2. The output dataset has column lineage that points to the (missing) input dataset
