### ISSUE TITLE
[DOCUMENTATION] Python client example uses old deprecated facets

### ISSUE THREAD

**Issue by skrawcz** [OpenLineage/OpenLineage#3026]
# what
https://openlineage.io/docs/client/python uses the deprecated `from openlineage.client.facet` import, rather than the newer `from openlineage.client.facet_v2` import.

# ideal 
https://openlineage.io/docs/client/python is updated to use the latest facet module.

**Comment by kacpermuda** [comment]
Hey @skrawcz thanks for the catch. Would you be open to providing a PR with the desired change? I’ll be happy to help if you encounter any blockers.

**Comment by skrawcz** [comment]
> Hey @skrawcz thanks for the catch. Would you be open to providing a PR with the desired change? I’ll be happy to help if you encounter any blockers.

If I get something I'm happy with, sure. Are there docs on the latest facet module that could explain any differences from the old one?

**Comment by kacpermuda** [comment]
I'm not sure if there are docs about it, but with the change to v2 facets they are being auto-generated from the [spec](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets) so this is something you may look at. This transition to v2 is fixing any discrepancies from the spec that we might have had before with the manual implementation of python classes.

**Comment by zhaomuzhi** [comment]
Hi @kacpermuda , I'm looking for how to auto generate v2 facets from [spec](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets), but didn't find any reference. Is the process documented anywhere?

**Comment by JDarDagran** [comment]
> Hi @kacpermuda , I'm looking for how to auto generate v2 facets from [spec](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets), but didn't find any reference. Is the process documented anywhere?

@zhaomuzhi, the process is not documented. It's being generated as pre-commit hook. See: https://github.com/OpenLineage/OpenLineage/blob/main/.pre_commit/generate-facets/generate.py

May I ask why would you like to auto generate the facets by yourself?

**Comment by zhaomuzhi** [comment]
> > Hi @kacpermuda , I'm looking for how to auto generate v2 facets from [spec](https://github.com/OpenLineage/OpenLineage/tree/main/spec/facets), but didn't find any reference. Is the process documented anywhere?
> 
> @zhaomuzhi, the process is not documented. It's being generated as pre-commit hook. See: https://github.com/OpenLineage/OpenLineage/blob/main/.pre_commit/generate-facets/generate.py
> 
> May I ask why would you like to auto generate the facets by yourself?

I see. I'm adding my own facet for testing locally.I feel it would be very helpful if there's a documented way of doing that before I commit. I would like to verify if the spec I define is correct by looking at the generated python code.

**Comment by zhaomuzhi** [comment]
@JDarDagran , I installed the `pre-commit` which got triggered when I commit, but I got this error, do you happen to know what's the issue?

```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/zhaomuzhi/src/OpenLineage/client/python/.venv/bin/python', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/zhaomuzhi/.cache/pre-commit/repor6koy21y/node_env-default')
return code: 1
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
        return self.sslsocket_class._create(
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

**Comment by JDarDagran** [comment]
@zhaomuzhi your issue seems unrelated to the original issue. Please let's move to Slack or separate issue.

The error you've got also seems unrelated to OL code rather then some system setup (certifi maybe?)
