### ISSUE TITLE
DatabricksEventFilter check on isDisabled blocked threads

### ISSUE THREAD

**Issue by mzheng-plaid** [OpenLineage/OpenLineage#3220]
**Details:**
We run Spark on EMR with OpenLineage and we saw logs of:
```
pool-37-thread-1" #106 prio=5 os_prio=0 tid=0x0000ffffa1073000 nid=0xc8 waiting for monitor entry [0x0000fff71f7d2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:166)
	- waiting to lock <0x0000fff7cd838f90> (a org.apache.spark.sql.execution.QueryExecution)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:166)
	at io.openlineage.spark.agent.filters.EventFilterUtils.lambda$getLogicalPlan$2(EventFilterUtils.java:44)
	at io.openlineage.spark.agent.filters.EventFilterUtils$$Lambda$3250/2059122199.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at io.openlineage.spark.agent.filters.EventFilterUtils.getLogicalPlan(EventFilterUtils.java:44)
	at io.openlineage.spark.agent.filters.DatabricksEventFilter.isSerializeFromObject(DatabricksEventFilter.java:67)
	at io.openlineage.spark.agent.filters.DatabricksEventFilter.isDisabled(DatabricksEventFilter.java:41)
	at io.openlineage.spark.agent.filters.EventFilterUtils.lambda$isDisabled$0(EventFilterUtils.java:35)
	at io.openlineage.spark.agent.filters.EventFilterUtils$$Lambda$3242/21183944.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:536)
	at io.openlineage.spark.agent.filters.EventFilterUtils.isDisabled(EventFilterUtils.java:36)
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:216)
	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$null$14(OpenLineageSparkListener.java:213)
	at io.openlineage.spark.agent.OpenLineageSparkListener$$Lambda$3241/1250792106.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

I can't tell if this is causing issues on the job, but based on https://github.com/OpenLineage/OpenLineage/blob/d1c97acf401fd7b8919bf86464b3e27e41e287e2/integration/spark/shared/src/main/java/io/openlineage/spark/agent/filters/DatabricksEventFilter.java#L40 it seems the checks should be skipped if `isRunOnDatabricksPlatform` is false? Or is the filter name a misnomer?

ie. can the code be changed to:
```
if !isRunOnDatabricksPlatform(event) {
    return false;
}
return isDisabledDatabricksPlan(event) || isSerializeFromObject() || isWriteIntoDeltaCommand();
```

All the other checks seem expensive to run if not necessary.

**Comment by mobuchowski** [comment]
Yeah - sounds like this is a good idea, @mzheng-plaid are you willing to provide a PR?
