### ISSUE TITLE
[BUG][SPARK] Spark SQL Commands for Output Delta Table Returning Incorrect Output Dataset or Missing Output Dataset

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#487]
We have spark SQL commands on Azure Databricks (DBR 9.1) which reads in a parquet file and then inserts those rows into a delta table.
```
%python
df = spark.read.parquet("abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet")
df.createOrReplaceTempView("dft")
%sql
Create database IF NOT EXISTS MYDATABASE;

CREATE TABLE IF NOT EXISTS MYDATABASE.DimOrganization (
  OrganizationKey int, 
  ParentOrganizationKey int,
  PercentageOfOwnership double,
  OrganizationName string,
  CurrencyKey int
)
USING DELTA
LOCATION 'abfss://outputdata1@MYSTORAGEACCT.dfs.core.windows.net/cummins/DimOrganization.delta'
%sql
insert into MYDATABASE.DimOrganization
Select * from dft
````

It looks like the error is with the Delta Catalog not being supported with the AppendData (missing OutputDataset) or ColumnToRow (returns the original source input and not the actual output dataset)

## Append Data
```
22/01/20 07:25:58 INFO OpenLineageRunEventBuilder: Visiting query plan Optional[== Parsed Logical Plan ==
'InsertIntoStatement 'UnresolvedRelation [MYDATABASE, DimOrganization], [], false, false, false
+- 'Project [*]
   +- 'UnresolvedRelation [dft], [], false

== Analyzed Logical Plan ==
num_affected_rows: bigint, num_inserted_rows: bigint
AppendData RelationV2[OrganizationKey#159, ParentOrganizationKey#160, PercentageOfOwnership#161, OrganizationName#162, CurrencyKey#163] MYDATABASE.dimorganization, false, true
+- Project [OrganizationKey#41, ParentOrganizationKey#42, PercentageOfOwnership#43, OrganizationName#44, CurrencyKey#45]
   +- SubqueryAlias dft
      +- Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet

== Optimized Logical Plan ==
AppendData RelationV2[OrganizationKey#159, ParentOrganizationKey#160, PercentageOfOwnership#161, OrganizationName#162, CurrencyKey#163] MYDATABASE.dimorganization, false, true
+- Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet

== Physical Plan ==
AppendDataExecV1 [num_affected_rows#176L, num_inserted_rows#177L], DeltaTableV2(org.apache.spark.sql.SparkSession@1fefb3d3,abfss://outputdata1@MYSTORAGEACCT.dfs.core.windows.net/MYDATABASE/DimOrganization.delta,Some(CatalogTable(
Database: MYDATABASE
Table: dimorganization
Owner: root
Created Time: Thu Jan 20 07:20:23 UTC 2022
Last Access: UNKNOWN
Created By: Spark 3.1.2
Type: EXTERNAL
Provider: delta
Table Properties: [delta.lastCommitTimestamp=1642663210000, delta.lastUpdateVersion=0, delta.minReaderVersion=1, delta.minWriterVersion=2]
Location: abfss://outputdata1@MYSTORAGEACCT.dfs.core.windows.net/MYDATABASE/DimOrganization.delta
Serde Library: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
InputFormat: org.apache.hadoop.mapred.SequenceFileInputFormat
OutputFormat: org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat
Partition Provider: Catalog
Schema: root
 |-- OrganizationKey: integer (nullable = true)
 |-- ParentOrganizationKey: integer (nullable = true)
 |-- PercentageOfOwnership: double (nullable = true)
 |-- OrganizationName: string (nullable = true)
 |-- CurrencyKey: integer (nullable = true)
)),Some(MYDATABASE.DimOrganization),None,org.apache.spark.sql.util.CaseInsensitiveStringMap@1f), [], Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet, org.apache.spark.sql.execution.datasources.v2.DataSourceV2Strategy$$Lambda$5771/1256868621@1cf453fc
] with output dataset builders []
22/01/20 07:25:58 INFO AppendDataVisitor: Matched io.openlineage.spark.agent.lifecycle.plan.AppendDataVisitor<org.apache.spark.sql.catalyst.plans.logical.AppendData,io.openlineage.client.OpenLineage$OutputDataset> to logical plan AppendData RelationV2[OrganizationKey#159, ParentOrganizationKey#160, PercentageOfOwnership#161, OrganizationName#162, CurrencyKey#163] MYDATABASE.dimorganization, false, true
+- Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet

22/01/20 07:25:58 INFO DataSourceV2RelationVisitor: Matched io.openlineage.spark3.agent.lifecycle.plan.DataSourceV2RelationVisitor<org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation,D> to logical plan RelationV2[OrganizationKey#159, ParentOrganizationKey#160, PercentageOfOwnership#161, OrganizationName#162, CurrencyKey#163] MYDATABASE.dimorganization

22/01/20 07:25:58 INFO DataSourceV2RelationVisitor: Matched io.openlineage.spark3.agent.lifecycle.plan.DataSourceV2RelationVisitor<org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation,D> to logical plan RelationV2[OrganizationKey#159, ParentOrganizationKey#160, PercentageOfOwnership#161, OrganizationName#162, CurrencyKey#163] MYDATABASE.dimorganization

22/01/20 07:25:58 ERROR PlanUtils3: Catalog com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog is unsupported
io.openlineage.spark3.agent.lifecycle.plan.catalog.UnsupportedCatalogException: com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.lambda$getDatasetIdentifier$2(CatalogUtils3.java:47)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:47)
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:33)
	at io.openlineage.spark3.agent.utils.PlanUtils3.getDatasetIdentifier(PlanUtils3.java:41)
	at io.openlineage.spark3.agent.utils.PlanUtils3.fromDataSourceV2Relation(PlanUtils3.java:85)
	at io.openlineage.spark3.agent.utils.PlanUtils3.fromDataSourceV2Relation(PlanUtils3.java:61)
	at io.openlineage.spark3.agent.lifecycle.plan.DataSourceV2RelationVisitor.apply(DataSourceV2RelationVisitor.java:34)
	at io.openlineage.spark3.agent.lifecycle.plan.DataSourceV2RelationVisitor.apply(DataSourceV2RelationVisitor.java:21)
	at io.openlineage.spark.agent.util.PlanUtils$1.apply(PlanUtils.java:78)
        <SNIP>
	at io.openlineage.spark.agent.util.PlanUtils.applyFirst(PlanUtils.java:46)
	at io.openlineage.spark.agent.lifecycle.plan.AppendDataVisitor.apply(AppendDataVisitor.java:24)
	at io.openlineage.spark.agent.lifecycle.plan.AppendDataVisitor.apply(AppendDataVisitor.java:15)
	at io.openlineage.spark.agent.util.PlanUtils$1.apply(PlanUtils.java:78)
        <SNIP>
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$visitLogicalPlan$13(OpenLineageRunEventBuilder.java:399)
	at io.openlineage.spark.agent.util.ScalaConversionUtils$3.apply(ScalaConversionUtils.java:126)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$buildOutputDatasets$14(OpenLineageRunEventBuilder.java:414)
	at java.util.Optional.map(Optional.java:215)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:414)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:308)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:293)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:248)
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:80)
	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:148)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:134)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1562)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
22/01/20 07:25:58 INFO CodeGenerator: Code generated in 8.296789 ms
22/01/20 07:25:58 INFO EventEmitter: Lineage completed successfully: ResponseMessage(responseCode=200, body="<SNIP>", error=null) {"eventType":"COMPLETE","eventTime":"2022-01-20T07:25:58.232Z","run":{"runId":"f49ae382-83b9-45cf-adf7-ccf0b5620f95","facets":{"spark_version":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet","spark-version":"3.1.2","openlineage-spark-version":"0.6.0-SNAPSHOT"},"spark.logicalPlan":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet","plan":[{"class":"org.apache.spark.sql.catalyst.plans.logical.AppendData","num-children":1,"table":[{"class":"org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation","num-children":0,"table":null,"output":[[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"OrganizationKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":159,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"ParentOrganizationKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":160,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"PercentageOfOwnership","dataType":"double","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":161,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"OrganizationName","dataType":"string","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":162,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"CurrencyKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":163,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}]],"catalog":null,"identifier":null,"options":null}],"query":0,"writeOptions":null,"isByName":false,"requireImplicitCasting":true},{"class":"org.apache.spark.sql.execution.datasources.LogicalRelation","num-children":0,"relation":null,"output":[[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"OrganizationKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":41,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"ParentOrganizationKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":42,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"PercentageOfOwnership","dataType":"double","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":43,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"OrganizationName","dataType":"string","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":44,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"CurrencyKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":45,"jvmId":"eefa0ea7-f831-45bf-8c1e-7ca74dc560aa"},"qualifier":[]}]],"isStreaming":false}]}}},"job":{"namespace":"adbpurviewol1","name":"databricks_shell.append_data_exec_v1","facets":{}},"inputs":[{"namespace":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net","name":"/DimOrganization.parquet","facets":{"dataSource":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet","name":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net","uri":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net"},"schema":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet","fields":[{"name":"OrganizationKey","type":"integer"},{"name":"ParentOrganizationKey","type":"integer"},{"name":"PercentageOfOwnership","type":"double"},{"name":"OrganizationName","type":"string"},{"name":"CurrencyKey","type":"integer"}]}},"inputFacets":{}}],"outputs":[],"producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunEvent"}
```

I attempted to resolve this by adding the following snippet to the DeltaHandler class (`integration\spark\src\main\spark3\java\io\openlineage\spark3\agent\lifecycle\plan\catalog\DeltaHandler.java`) but it did not resolve the issue.

```scala
public boolean hasClasses() {
  public boolean hasClasses() {
    try {
      DeltaHandler.class
          .getClassLoader()
          .loadClass("org.apache.spark.sql.delta.catalog.DeltaCatalog");
      return true;
    } catch (Exception e) {
      // swallow- we don't care
    }
    // ADDITION: Handle Databricks
    try {
      DeltaHandler.class
          .getClassLoader()
          .loadClass("com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog");
      return true;
    } catch (Exception e) {
      // swallow- we don't care
    }
    return false;
  }
```

## ColumnarToRow

Note in this case that the ABFS File System is looking at a rawdata container and an outpudata container but the output only contains / points to the rawdata container and the wrong folder path.  It looks like this is an unhandled command for Delta?

```
22/01/20 07:53:26 INFO OpenLineageRunEventBuilder: Visiting query plan Optional[== Parsed Logical Plan ==
Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet

== Analyzed Logical Plan ==
OrganizationKey: int, ParentOrganizationKey: int, PercentageOfOwnership: double, OrganizationName: string, CurrencyKey: int
Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet

== Optimized Logical Plan ==
Relation[OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] parquet

== Physical Plan ==
*(1) ColumnarToRow
+- FileScan parquet [OrganizationKey#41,ParentOrganizationKey#42,PercentageOfOwnership#43,OrganizationName#44,CurrencyKey#45] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<OrganizationKey:int,ParentOrganizationKey:int,PercentageOfOwnership:double,OrganizationNam...
] with output dataset builders []
22/01/20 07:53:26 INFO AzureBlobFileSystem:V3: Initializing AzureBlobFileSystem for abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet with credential = SharedKeyCredentials;1460318952 with jvmId = 654
22/01/20 07:53:26 INFO AzureBlobFileSystem:V3: Initializing AzureBlobFileSystem for abfss://outputdata1@MYSTORAGEACCT.dfs.core.windows.net/MYDATABSE/DimOrganization.delta with credential = SharedKeyCredentials;1460318952 with jvmId = 654
22/01/20 07:53:26 INFO ClusterLoadAvgHelper: Current cluster load: 1, Old Ema: 1.0, New Ema: 1.0 
22/01/20 07:53:26 INFO DeltaParquetFileFormat: Using user defined output committer for Parquet: org.apache.spark.sql.parquet.DirectParquetOutputCommitter
22/01/20 07:53:26 INFO EventEmitter: Lineage completed successfully: ResponseMessage(responseCode=200, body="<SNIP>", error=null) {"eventType":"START","eventTime":"2022-01-20T07:53:26.327Z","run":{"runId":"45d1bc5b-f903-4079-8374-f174680e3131","facets":{"spark_version":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet","spark-version":"3.1.2","openlineage-spark-version":"0.6.0-SNAPSHOT"},"spark.logicalPlan":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet","plan":[{"class":"org.apache.spark.sql.execution.datasources.LogicalRelation","num-children":0,"relation":null,"output":[[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"OrganizationKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":41,"jvmId":"aeb07a0b-7dd6-4240-8eb6-6811ef1a4a6d"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"ParentOrganizationKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":42,"jvmId":"aeb07a0b-7dd6-4240-8eb6-6811ef1a4a6d"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"PercentageOfOwnership","dataType":"double","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":43,"jvmId":"aeb07a0b-7dd6-4240-8eb6-6811ef1a4a6d"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"OrganizationName","dataType":"string","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":44,"jvmId":"aeb07a0b-7dd6-4240-8eb6-6811ef1a4a6d"},"qualifier":[]}],[{"class":"org.apache.spark.sql.catalyst.expressions.AttributeReference","num-children":0,"name":"CurrencyKey","dataType":"integer","nullable":true,"metadata":{},"exprId":{"product-class":"org.apache.spark.sql.catalyst.expressions.ExprId","id":45,"jvmId":"aeb07a0b-7dd6-4240-8eb6-6811ef1a4a6d"},"qualifier":[]}]],"isStreaming":false}]}}},"job":{"namespace":"adbpurviewol1","name":"databricks_shell.columnar_to_row","facets":{}},"inputs":[{"namespace":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net","name":"/DimOrganization.parquet","facets":{"dataSource":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet","name":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net","uri":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net"},"schema":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet","fields":[{"name":"OrganizationKey","type":"integer"},{"name":"ParentOrganizationKey","type":"integer"},{"name":"PercentageOfOwnership","type":"double"},{"name":"OrganizationName","type":"string"},{"name":"CurrencyKey","type":"integer"}]}},"inputFacets":{}}],"outputs":[{"namespace":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net","name":"/DimOrganization.parquet","facets":{"dataSource":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet","name":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net","uri":"abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net"},"schema":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet","fields":[{"name":"OrganizationKey","type":"integer"},{"name":"ParentOrganizationKey","type":"integer"},{"name":"PercentageOfOwnership","type":"double"},{"name":"OrganizationName","type":"string"},{"name":"CurrencyKey","type":"integer"}]}},"outputFacets":{}}],"producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark","schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunEvent"}
```

**Comment by mobuchowski** [comment]
ColumnarToRow probably isn't the culprit.

Is this delta catalog an alias to this one that we support?

https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala

I don't really see code of this databricks delta catalog in the open.

@wjohnson instead of only adding to hasClasses, could you copy the whole class as DatabricksDeltaHandler, use this class in isDefined and apply too?

**Comment by mobuchowski** [comment]
Looking at it again, I think that would be reasonable approach considering we're only using this `DeltaCatalog` here for just one method call. @collado-mike at separate thread looked at this jar and everything seemed to match the open source implementation (not the same class though...).

So, in the `DeltaDatabricksHandler` I'd change `hasClasses` to what I've wrote earlier, `isClass` to something like 

```java
  @Override
  public boolean isClass(TableCatalog tableCatalog) {
    return tableCatalog.getClass().getCanonicalName().equals("com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog");
  }
```

and `getDatasetIdentifier` to 

```java
  @Override
  public DatasetIdentifier getDatasetIdentifier(
      SparkSession session,
      TableCatalog tableCatalog,
      Identifier identifier,
      Map<String, String> properties) {

    Optional<String> location;
    boolean isPathIdentifier = false;
    try {
       isPathIdentifier = (boolean) MethodUtils.invokeMethod(tableCatalog, true, "isPathIdentifier", identifier);
    } catch (InvocationTargetException | IllegalAccessException | NoSuchMethodException e) {
      ...;
    }
    if (isPathIdentifier) {
      location = Optional.of(identifier.name());
    } else {
      location = Optional.ofNullable(properties.get("location"));
    }

    ...
```



https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/reflect/MethodUtils.html#invokeExactMethod-java.lang.Object-java.lang.String-java.lang.Object:A-java.lang.Class:A-

**Comment by wjohnson** [comment]
🥳Looking like this solves it, @mobuchowski !  I'll put in a PR for these changes.  I'm not sure if there's a test we should put into place to confirm the behavior.

## Before Changes Described in this Issue (OpenLineage 0.5.1)
```
{
            "job": 1,
            "name": "databricks_shell.columnar_to_row",
            "inputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ],
            "outputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ]
        },
        {
            "job": 2,
            "name": "databricks_shell.columnar_to_row",
            "inputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ],
            "outputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ]
        }
```
The critical part is that we are missing the Append Data task that actually inserts into the database / correct file system.  I'm not 100% sure what the columnar to row task is doing in this case. It looks like it's just an in memory operation perhaps?


## After Changes Described in this Issue
```
 {
            "job": 1,
            "inputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ],
            "outputs": [
                "abfss://outputdata1@MYSTORAGEACCT.dfs.core.windows.net/MYDB/DimOrganization.delta"
            ]
        },
        {
            "job": 2,
            "name": "databricks_shell.columnar_to_row",
            "inputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ],
            "outputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ]
        },
        {
            "job": 3,
            "name": "databricks_shell.columnar_to_row",
            "inputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ],
            "outputs": [
                "abfss://rawdata@MYSTORAGEACCT.dfs.core.windows.net/DimOrganization.parquet"
            ]
        }
```

**Comment by mobuchowski** [comment]
> I'm not sure if there's a test we should put into place to confirm the behavior.

At some point we would like to have actual integration tests that would confirm that everything works nice on Azure Databricks, as I think this is untestable without actual cloud integration. 

> I'm not 100% sure what the columnar to row task is doing in this case. It looks like it's just an in memory operation perhaps?

Looks like it's something purely existing in physical part of the plan, when we use column-based source files like parquet.
