### ISSUE TITLE
[BUG][SPARK] TableContentChangeVisitor Does Not Handle Delta Tables

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#497]
In an Azure Databricks cluster (Databricks Runtime 9.1), it fails to return lineage for sql statements like `INSERT OVERWRITE mytable SELECT * FROM othertable` when `mytable` is a `DELTA` table.

I am also unable to successfully emit lineage when testing locally on Spark 3.1.2.  I've provided a script and stacktrace below based on a local test.  I do not receive the same error messages on Databricks but maybe solving it locally will help.

As I stepped through this issue, it looks like the `DeltaHandler` class is failing to load my `org.apache.spark.sql.delta.catalog.DeltaCatalog` class (ClassNotFoundException from the `loadClass()` method) which causes it to get filtered in the `CatalogUtils3.getHandlers` method.

#### Script to Reproduce Error

Started a local Spark cluster:

```bash
spark-shell \
--master local[4] \
--packages "io.delta:delta-core_2.12:1.0.0" \
--conf spark.driver.extraClassPath=./build/libs/openlineage-spark-0.6.0-SNAPSHOT.jar \
--conf spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener \
--conf spark.openlineage.namespace=adbpurviewol1 \
--conf spark.openlineage.version=1 \
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
--conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
```

Executed the following snippet:

```scala
spark.sql("CREATE TABLE testtable( id INT ) USING DELTA LOCATION '/tmp/testtable'")
val df = Seq((1),(2),(3)).toDF("id")
df.createOrReplaceTempView("mydata")
// Results in a OverwriteByExpression Logical Plan
spark.sql("INSERT OVERWRITE testtable SELECT * FROM mydata")
```

#### Stacktrace

```
 22/01/26 21:32:00 ERROR PlanUtils3: Catalog org.apache.spark.sql.delta.catalog.DeltaCatalog is unsupported
io.openlineage.spark3.agent.lifecycle.plan.catalog.UnsupportedCatalogException: org.apache.spark.sql.delta.catalog.DeltaCatalog
        at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.lambda$getDatasetIdentifier$2(CatalogUtils3.java:48)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:48)
        at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:34)
        at io.openlineage.spark3.agent.utils.PlanUtils3.getDatasetIdentifier(PlanUtils3.java:41)
        at io.openlineage.spark3.agent.utils.PlanUtils3.fromDataSourceV2Relation(PlanUtils3.java:85)
        at io.openlineage.spark3.agent.lifecycle.plan.TableContentChangeVisitor.apply(TableContentChangeVisitor.java:74)
        at io.openlineage.spark3.agent.lifecycle.plan.TableContentChangeVisitor.apply(TableContentChangeVisitor.java:26)
        at io.openlineage.spark.agent.util.PlanUtils$1.apply(PlanUtils.java:78)
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
        at scala.runtime.AbstractPartialFunction.applyOrElse(AbstractPartialFunction.scala:30)
        at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:194)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$visitLogicalPlan$13(OpenLineageRunEventBuilder.java:399)
        at io.openlineage.spark.agent.util.ScalaConversionUtils$3.apply(ScalaConversionUtils.java:126)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$buildOutputDatasets$14(OpenLineageRunEventBuilder.java:414)
        at java.util.Optional.map(Optional.java:215)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:414)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:308)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:293)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:248)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:80)
        at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:148)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:134)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

**Comment by wjohnson** [comment]
If it's okay to mention someone, @pawel-big-lebowski wrote the `TableContentChangeVisitor` and might have some insights.

**Comment by pawel-big-lebowski** [comment]
Hi Will, 

Visitor classes should work regardless the provider underneath. I modified integration test to use delta instead of iceberg and it's working  (https://github.com/OpenLineage/OpenLineage/pull/498/files) as you can see the CI tests passing. 

The test modified in PR does exactly the same as the one you specified within an issue. 
Are you able to spot any difference?

**Comment by wjohnson** [comment]
@pawel-big-lebowski - I'm obviously doing something wrong. When I use the jar off the latest commit on main, everything seems to be working fine.  I'll close this issue as I'm unblocked but still confused as to what I was doing wrong. Thank you for your effort and proving out that everything is working as expected.
