### ISSUE TITLE
[BUG] SnowflakeOperator no longer reporting Lineage in Airflow 2.2

### ISSUE THREAD

**Issue by conorbev** [OpenLineage/OpenLineage#500]
In recent Airflow versions (certainly in `2.2`, but I think possibly `2.1.4` also) if you use the `SnowflakeOperator` with `OpenLineageBackend` `0.5.1` you'll get an exception in the log like:

```
ERROR - Failed to extract metadata 'SnowflakeOperator' object has no attribute 'get_hook'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openlineage/lineage_backend/__init__.py", line 83, in _extract_metadata
    task_metadata = self._extract(extractor, task_instance)
  File "/usr/local/lib/python3.9/site-packages/openlineage/lineage_backend/__init__.py", line 104, in _extract
    task_metadata = extractor.extract_on_complete(task_instance)
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/base.py", line 61, in extract_on_complete
    return self.extract()
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 65, in extract
    authority=self._get_authority(),
  File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/extractors/snowflake_extractor.py", line 38, in _get_authority
    return self.operator.get_hook()._get_conn_params()['account']
AttributeError: 'SnowflakeOperator' object has no attribute 'get_hook'
```

This [PR](https://github.com/apache/airflow/pull/17741) changed the method from `get_hook()` to `get_db_hook()` so I believe OpenLineage will have to check for the presence of either method to work across Airflow versions.

**Comment by wslulciuc** [comment]
Assigned to [@denimalpaca](https://github.com/denimalpaca)
