### ISSUE TITLE
[INTEGRATION][SPARK][3.2.1]-ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.AlterTable

### ISSUE THREAD

**Issue by Grudra1** [OpenLineage/OpenLineage#642]
I am trying to test the Openlineage integration with Spark 3.2.1 (on a bitnami image). My pyspark code runs fine when I am not setting the extralistner option for Openlineage. However, if I add that option, my code breaks. I am using the io.openlineage:openlineage-spark:0.6.2 package for this. Error trace is as below : 

Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.AlterTable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 48 more
Exception in thread "spark-listener-group-shared" java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/AlterTable
        at io.openlineage.spark3.agent.lifecycle.plan.AlterTableDatasetBuilder.isDefinedAtLogicalPlan(AlterTableDatasetBuilder.java:29)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.isDefinedAt(AbstractQueryPlanDatasetBuilder.java:80)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.lambda$apply$0(AbstractQueryPlanDatasetBuilder.java:66)
        at java.util.Optional.map(Optional.java:215)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:59)
        at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:33)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$null$21(OpenLineageRunEventBuilder.java:467)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:422)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:313)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:298)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:276)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:167)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onJobEnd(OpenLineageSparkListener.java:210)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:39)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1404)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.AlterTable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 48 more

Am I missing something here ? I was hopeful about spark 3.2.1 seeing https://github.com/OpenLineage/OpenLineage/pull/607

**Comment by mobuchowski** [comment]
Hey @Grudra1 - #607 is not yet released. The same bug you've posted is fixed on main.

**Comment by Grudra1** [comment]
Hi @mobuchowski , thanks for your swift reply!
I didn't understand the second part of your reply, if it is fixed in main, then would adding the package dependency be not enough to see that fix ? I am currently passing **_--packages io.openlineage:openlineage-spark:0.6.2_** while doing spark-submit and within my code I have added the extra configs as mentioned in the docs : 
    **_('spark.extraListeners', 'io.openlineage.spark.agent.OpenLineageSparkListener'),
    ('spark.openlineage.url', 'http://localhost:3020/api/v1/namespaces/spark_integration/'),
    ('spark.openlineage.namespace', 'spark_integration'),_**

Am I doing it wrong ? Or should I wait for any future release which is on the way ?

Thanks for your attention !!

**Comment by mobuchowski** [comment]
>Or should I wait for any future release which is on the way ?

Yes, the changes on main are not yet released. It will be included in 0.7 release.

**Comment by kylemart** [comment]
Hey @mobuchowski, is there a defined cadence for releases? Wondering when 0.7 will be released :)
