### ISSUE TITLE
[Bug][Airflow] Extractor seems to be running before the operator has completed execution

### ISSUE THREAD

**Issue by pankajkoti** [OpenLineage/OpenLineage#736]
I am kind of seeing an error where it appears that the extractor seems to be running before the operator has completed.
I am trying the build with `Airflow 2.3.0` & `OpenLineage 0.8.1`
I am trying the `BigQuery` operator where it creates and attaches the connection hook while the operator is executing: https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/operators/bigquery.py#L2143

I am relying on the same hook in the extractor https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/google/cloud/extractors/bigquery_async_extractor.py#L33 . 
It was running fine with version `0.6.2` . However, now I see and am guessing that the extractor starts before even the hook is attached to the operator and as a result it does not enter that code block where the extractor tries to use the operator's hook to establish connection with Google Cloud & falls to the below placeholder line Client()

**Comment by pankajkoti** [comment]
The operator does set XCOM and the extractor is able to pull this XCOM. Once the job ID is fetched from the XCOM, the extractor tries to get metadata from Google cloud against the job ID. To do so, it needs a client which it is able to get from the hook in version `0.6.2` after the operator has completed processing (Attaching the hook to the operator is part of the operator execution). 

Now, like it seems that the extractor execution starts before the operator has finished processing (it has not attached the hook to itself yet), it is not able to get the appropriate client. 

Attaching logs for your reference:
`
[2022-05-09, 13:48:38 UTC] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
[2022-05-09, 13:48:38 UTC] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
[2022-05-09, 13:48:38 UTC] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
[2022-05-09, 13:48:38 UTC] {_default.py:286} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING - Exception in thread Thread-1:
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING - Traceback (most recent call last):
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     self.run()
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/threading.py", line 910, in run
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     self._target(*self._args, **self._kwargs)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/openlineage/***/listener.py", line 82, in on_running
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     task_metadata = extractor_manager.extract_metadata(dagrun, task)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/openlineage/***/extractors/manager.py", line 26, in extract_metadata
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     extractor = self._get_extractor(task)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/openlineage/***/extractors/manager.py", line 76, in _get_extractor
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     self.extractors[task.task_id] = extractor(task)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/***/astronomer_providers/astronomer/providers/google/cloud/extractors/bigquery_async_extractor.py", line 25, in __init__
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     self._big_query_client = self._get_big_query_client()
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/***/astronomer_providers/astronomer/providers/google/cloud/extractors/bigquery_async_extractor.py", line 36, in _get_big_query_client
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     return Client()
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 231, in __init__
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     super(Client, self).__init__(
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 320, in __init__
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 268, in __init__
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     project = self._determine_default(project)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     return _determine_default_project(project)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     _, project = google.auth.default()
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 488, in default
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING -     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
[2022-05-09, 13:48:38 UTC] {logging_mixin.py:115} WARNING - google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started`

**Comment by pankajkoti** [comment]
Okay @mobuchowski , thanks for the suggestion. That seems to work. However, the previous version used to work fine . Would like to connect with you to understand the design change and intent.
