### ISSUE TITLE
spark: Integration failing with Spark 3.2 on Databricks

### ISSUE THREAD

**Issue by VinithKrishnan** [OpenLineage/OpenLineage#764]
Encountered the following error on Databricks Runtime 10.4 using open lineage version 8.1.
StdErr Output :
`ERROR Uncaught throwable from user code: java.lang.NullPointerException
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.CACHE_EXPIRATION_TIME(DeltaValidation.scala:46)
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.<init>(DeltaValidation.scala:60)
	at com.databricks.sql.transaction.tahoe.DeltaValidation$.<clinit>(DeltaValidation.scala)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:287)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:250)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:892)`

Log4j Driver logs:
`uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/CreateV2Table
	at io.openlineage.spark3.agent.lifecycle.plan.CreateReplaceDatasetBuilder.isDefinedAtLogicalPlan(CreateReplaceDatasetBuilder.java:41)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.isDefinedAt(AbstractQueryPlanDatasetBuilder.java:80)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.lambda$apply$0(AbstractQueryPlanDatasetBuilder.java:66)
	at java.util.Optional.map(Optional.java:215)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:59)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:33)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$null$21(OpenLineageRunEventBuilder.java:467)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:422)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:313)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:298)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:250)
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:82)
	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:97)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:83)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1612)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
`

I get the following output from the cluster:
`The spark context has stopped and the driver is restarting.`

**Comment by mobuchowski** [comment]
I think this should be fixed in 0.11 - @VinithKrishnan want to check?

**Comment by Anirudh181001** [comment]
Hi, I am still facing this issue in 0.17 @mobuchowski

**Comment by Anirudh181001** [comment]
@mobuchowski  Hi, it was a java version mismatch error on my end. It works fine now! Thanks!

**Comment by pawel-big-lebowski** [comment]
Yesterday, we've merged integration test to verify our spark integration on databricks -> https://github.com/OpenLineage/OpenLineage/pull/1928

The test runs on Spark 3.4 and databricks cluster 13.0.x-scala2.12. We plan to create more tests whenever new issues occur. Is this issue still valid? Can we close it?
