### ISSUE TITLE
[CLIENT][JAVA] `NoClassDefFoundError` when using `OpenLineageClient.Builder` 

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#899]
When instantiating an new OL client object  using `OpenLineageClient.Builder` 

```java
OpenLineageClient olClient =
  OpenLineageClient.builder().transport(HttpTransport.builder().uri(olUrl).build()).build();
```

the following `NoClassDefFoundError` is thrown:

```
$ java -jar ./api/build/libs/marquez-api-0.21.1-SNAPSHOT.jar seed
java.lang.NoClassDefFoundError: io/openlineage/client/shaded/com/fasterxml/jackson/core/JsonFactory
	at io.openlineage.client.transports.HttpTransport$Builder.<clinit>(HttpTransport.java:108)
	at io.openlineage.client.transports.HttpTransport.builder(HttpTransport.java:93)
	at marquez.cli.SeedCommand.run(SeedCommand.java:74)
	at marquez.cli.SeedCommand.run(SeedCommand.java:38)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at marquez.MarquezApp.main(MarquezApp.java:53)
Caused by: java.lang.ClassNotFoundException: io.openlineage.client.shaded.com.fasterxml.jackson.core.JsonFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 8 more
```

Note, we [relocate](https://github.com/OpenLineage/OpenLineage/blob/main/client/java/build.gradle#L140) the dependencies when building the `jar`.

**Comment by wslulciuc** [comment]
Closing this issue. I was using `0.8.1`, bumping to `0.10.0` fixed the issue.
