### ISSUE TITLE
airflow: OpenLineage 0.10.0 and airflow 2.3.3 Failed to import plugin

### ISSUE THREAD

**Issue by seanmuth** [OpenLineage/OpenLineage#968]
Seeing error:

```
Failed to import shared.extractors.ol_custom_extractors_0_10_0.QueryOperatorExtractor
```

Extractor imports:

```
import logging
from typing import Optional, List
from openlineage.airflow.extractors.base import BaseExtractor,TaskMetadata
from openlineage.client.facet import SqlJobFacet, ExternalQueryRunFacet
from openlineage.common.sql import SqlMeta, parse, DbTableMeta
from openlineage.common.dataset import Source, Dataset
from openlineage.common.models import DbTableSchema, DbColumn
from openlineage.airflow.utils import get_normalized_postgres_connection_uri, get_connection, safe_import_airflow
from urllib.parse import urlparse

from airflow.hooks.mysql_hook import MySqlHook
```

is the `MySqlHook` top-level airflow import causing circular imports as noted in #872?

**Comment by mobuchowski** [comment]
@seanmuth it can be. Most common issues that can cause this are

- wrong path to extractor in `OPENLINEAGE_EXTRACTORS`
- circular import: basically when Airflow imports OpenLineage plugin it's already very deep inside it's own imports  

You can't assume that you can import anything you could do inside DAG code for example. Good practice when importing from Airflow in extractors is import everything you need for type checking behind `typing.TYPE_CHECKING` flag, and everything else locally inside `extract`.

**Comment by seanmuth** [comment]
@mobuchowski we tried importing with `from dags.shared.extractors.ol_custom_extractors_0_10_0 import QueryOperatorExtractor` and got the following:

```
2022-08-02 18:21:16,032] {plugins_manager.py:235} ERROR - Failed to import plugin OpenLineagePlugin
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/airflow/plugins_manager.py", line 227, in load_entrypoint_plugins
plugin_class = entry_point.load()
File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 203, in load
module = import_module(match.group('module'))
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/plugin.py", line 12, in <module>
from openlineage.airflow.macros import lineage_parent_id, lineage_run_id
File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/macros.py", line 6, in <module>
from openlineage.airflow.utils import JobIdMapping, openlineage_job_name, safe_import_airflow
File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/utils.py", line 18, in <module>
from openlineage.airflow.facets import AirflowVersionRunFacet, AirflowRunArgsRunFacet
File "/usr/local/lib/python3.9/site-packages/openlineage/airflow/facets.py", line 10, in <module>
from openlineage.airflow import __version__ as OPENLINEAGE_AIRFLOW_VERSION
ImportError: cannot import name '__version__' from partially initialized module 'openlineage.airflow' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/openlineage/airflow/__init__.py)
```

**Comment by collado-mike** [comment]
@seanmuth, where is that import statement? Is it in the DAG itself?

**Comment by seanmuth** [comment]
@collado-mike  no that import was just from a python shell on the scheduler pod

**Comment by collado-mike** [comment]
I see. And is the extractor itself trying to import the `OpenLineagePlugin`? What OpenLineage imports are present in the extractor file?

**Comment by mobuchowski** [comment]
Where are you actually importing extractor?

Extractors should be added by `OPENLINEAGE_EXTRACTORS` env variable or [here](https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/openlineage/airflow/extractors/extractors.py) if adding to core OpenLineage integration.

This can cause problems though; importing from top level package `__init__` should be only for external APIs. 

`from openlineage.airflow import __version__ as OPENLINEAGE_AIRFLOW_VERSION`
